[[home-dirs-main]]
= Deployment `home-dirs` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Tweak readme syntax
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:url_dd: https://github.com/divine-dotfiles/divine-dotfiles

The `home-dirs` deployment maintains a stable tree of personal directories under the home directory.

[[home-dirs-mtdt]]
[none]
* *Deployment* link:{url_dd}#mtdt-name-and-desc[*name*]: `home-dirs`
* link:{url_dd}#mtdt-priority[*Priority*]: `500`
* link:{url_dd}#mtdt-flags[*Flags*]: _none_
* link:{url_dd}#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `link:{url_dd}#fmwk-state[state]/bundles/divine-bundles/essentials/home-dirs/`
* link:{url_dd}#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `~/link:{url_dd}#fmwk-grail[.grail]/assets/home-dirs/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* link:{url_dd}#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `link:{url_dd}#fmwk-state[state]/backups/home-dirs/`
* link:{url_dd}#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* link:{url_dd}#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `home-dirs` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Creating*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `*_<dir-path>_*` entries from `<<home-dirs-mtdt,_<asset-dir>_>>/*home-dirs.cfg*`
! =>
! `~/*_<dir-path>_*/`
! 

!===

Installation:: Created, or re-used if pre-existing.
Removal:: Removed, or untouched if re-used.

|===

The `home-dirs` deployment:

* parses the `*home-dirs.cfg*` file as a link:{url_dd}#queue-mnf[queue manifest];
* treats entries as relative paths;
* ensures that the paths correspond to sub-directories under the home directory.

== Included assets

The `home-dirs.cfg` is a link:{url_dd}#queue-mnf[queue manifest].
It uses the key-value pairs to denote sections or entries that are only relevant for particular OS's.
By default, every entry is relevant everywhere.

A whitespace-separated list of OS's may be provided.
The entire list may be negated by prepenting it with an exclamation mark (`!`).

A key-value that appears on a line of its own comes into effect for the remainder of the manifest, or until overridden.
A key-value on the same line with an entry affects only that entry.

[source]
----
(os: debian)        relative/path/to/directory1   # Debian only
(os: macos bsd)     relative/path/to/directory2   # macOS/BSD only
(os: ! wsl cygwin)  relative/path/to/directory3   # Everything except WSL or Cygwin
(os: all)           relative/path/to/directory4   # 'all'/'any' are reserved values that denote any OS
----

[.note]
[%noheader,cols="<.<a"]
|===
| The queue manifest syntax is documented in the framework's link:{url_dd}#queue-mnf[documentation].
|===

== Dependencies

The `home-dirs` deployment is stand-alone.