= Deployment `home-dirs` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `home-dirs` deployment maintains a stable tree of personal directories under the home directory.

The `home-dirs` deployment has the priority of `*500*`.

== Deployment installation notes

The `home-dirs` deployment:

* parses the `*home-dirs.cfg*` file (located in the asset directory);
* extracts the relative paths for the current OS;
* ensures that each of those relative paths corresponds to a sub-directory in the home directory.

.Map of asset installation for the `home-dirs` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*home-dirs.cfg*`
| used
| _N/A_
| The manifest of home directories

|===

== Included assets

The `home-dirs` deployment's *asset directory* is located at `grail/assets/home-dirs`.

The `home-dirs.cfg` is a https://github.com/no-simpler/divine-dotfiles#queue-mnf[queue manifest].
It uses the key-value pairs to denote sections or entries that are only relevant for particular OS's.
By default, every entry is relevant everywhere.

A whitespace-separated list of OS's may be provided.
The entire list may be negated by prepenting it with an exclamation mark (`!`).

A key-value that appears on a line of its own comes into effect for the remainder of the manifest, or until overridden.
A key-value on the same line with an entry affects only that entry.

[source]
----
(os: debian)        relative/path/to/directory1   # Debian only
(os: macos bsd)     relative/path/to/directory2   # macOS/BSD only
(os: ! wsl cygwin)  relative/path/to/directory3   # Everything except WSL or Cygwin
(os: all)           relative/path/to/directory4   # 'all'/'any' are reserved values that denote any OS
----

[.note]
[%noheader,cols="<.<a"]
|===
| Refer to the framework https://github.com/no-simpler/divine-dotfiles[documentation] for more information on the queue manifest syntax.
|===

== Dependencies

The `home-dirs` deployment is stand-alone.

== Supported asset modifications

The directory manifest may be freely modified in the asset directory.
For the changes to take effect, the deployment must be (re-)installed.
Renaming or moving the manifest will break it.

== Overwriting policy

The `home-dirs` deployment does not touch any pre-existing files/directories at the desired paths.

== Deployment removal notes

The `home-dirs` deployment takes _extra_ care with removing directories.
The user is prompted before removing any non-empty directory.
The prompt is not affected by the intervention options and always appears.

The removal does not touch anything in the asset directory.