[[bash-it-main]]
= Deployment `bash-it` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.29
:revremark: Revise Grail references to reflect its move to home dir
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `bash-it` deployment introduces the https://github.com/Bash-it/bash-it[Bash-it framework] and custom assets for it into the home directory.

[[bash-it-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `bash-it`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `3333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/bash-it/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `~/https://github.com/no-simpler/divine-dotfiles#fmwk-grail[.grail]/assets/bash-it/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/bash-it/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `bash-it` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/Bash-it/bash-it[`Bash-it/bash-it`]
! =>
! `~/**.bash-it**/`
! <<bash-it-fmwk,^1^>>

!===

Installation:: Cloned/downloaded; any pre-existing original backed up and replaced.
Removal:: Displaced; any backed up original restored.

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<bash-it-mtdt,_<asset-dir>_>>/aliases/**__<name>__.aliases.bash**`
! =>
! `~/.bash-it/aliases/available/**__<name>__.aliases.bash**`
.4+! <<bash-it-blanks,^2^>>

! `<<bash-it-mtdt,_<asset-dir>_>>/completion/**__<name>__.completion.bash**`
! =>
! `~/.bash-it/completion/available/**__<name>__.completion.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/lib/**__<name>__.bash**`
! =>
! `~/.bash-it/lib/**__<name>__.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/plugins/**__<name>__.plugin.bash**`
! =>
! `~/.bash-it/plugins/available/**__<name>__.plugin.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/themes/**__<name>__**/__<name>__.theme.bash`
! =>
! `~/.bash-it/themes/**__<name>__**/`
! <<bash-it-themes,^3^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

The `bash-it` deployment clones or downloads the https://github.com/Bash-it/bash-it[`Bash-it/bash-it`] repository into the `~/.bash-it/` directory.
Having succeeded, it symlinks additional assets into the framework.

[[bash-it-fmwk]]
The Bash-it framework is installed with its included installation script.
The `--no-modify-config` option is added because the current bundle already includes the necessary initialization commands.

== Included assets

[[bash-it-blanks]]
Blank sample files are provided for each kind of custom assets:

- `*aliases/divine.aliases.bash*`
- `*completion/divine.completion.bash*`
- `*lib/divine.bash*`
- `*plugins/divine.plugin.bash*`

[[bash-it-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare/laidbare.theme.bash*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `bash-it` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved Bash-it framework is initialized from the runcom script at `~/https://github.com/no-simpler/divine-dotfiles#fmwk-grail[.grail]/assets/config-shell/01-bash-it.bash`.
The same file may and should be used to customize the Bash-it framework's loadout.