= Deployment `bash-it` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `bash-it` deployment introduces the https://github.com/Bash-it/bash-it[Bash-it framework] and custom assets for it into the home directory.

The `bash-it` deployment has the priority of `*3333*`.

== Deployment installation notes

The `bash-it` deployment clones or downloads the https://github.com/Bash-it/bash-it[`Bash-it/bash-it`] repository into the `~/.bash-it/` directory.
Having succeeded, it symlinks additional assets into the framework.

.Map of asset installation for the `bash-it` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| https://github.com/Bash-it/bash-it[Bash-it repo]
| cloned
| `~/**.bash-it**/`
| Bash-it framework <<bash-it-fmwk,^1^>>

| `aliases/**__<name>__.aliases.bash**`
| symlinked
| `~/.bash-it/aliases/available/**__<name>__.aliases.bash**`
| Custom Bash aliases <<bash-it-blanks,^2^>>

| `completion/**__<name>__.completion.bash**`
| symlinked
| `~/.bash-it/completion/available/**__<name>__.completion.bash**`
| Custom Bash completions <<bash-it-blanks,^2^>>

| `lib/**__<name>__.bash**`
| symlinked
| `~/.bash-it/lib/**__<name>__.bash**`
| Custom Bash-it lib scripts <<bash-it-blanks,^2^>>

| `plugins/**__<name>__.plugin.bash**`
| symlinked
| `~/.bash-it/plugins/available/**__<name>__.plugin.bash**`
| Custom Bash-it plugins <<bash-it-blanks,^2^>>

| `themes/**__<name>__**/__<name>__.theme.bash`
| symlinked
| `~/.bash-it/themes/**__<name>__**/`
| Custom Bash-it themes <<bash-it-themes,^3^>>

|===

The path components in bold designate the source and the target of cloning/symlinking.

[[bash-it-fmwk]]
The Bash-it framework is installed with its included installation script.
The `--no-modify-config` option is added because the current bundle already includes the necessary initialization commands.

== Included assets

The `bash-it` deployment's *asset directory* is located at `grail/assets/bash-it`.

[[bash-it-blanks]]
Blank sample files are provided for each kind of custom assets:

- `*aliases/divine.aliases.bash*`
- `*completion/divine.completion.bash*`
- `*lib/divine.bash*`
- `*plugins/divine.plugin.bash*`

[[bash-it-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare/laidbare.theme.bash*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `bash-it` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The retrieved Bash-it framework is initialized from the runcom script at `grail/assets/config-shell/01-bash-it.bash`.
The same file may and should be used to customize the Bash-it framework's loadout.

== Supported asset modifications

All symlinked assets may be freely modified in the asset directory; the modifications will take effect after the shell reload.

However, moving any of the assets will break them.
The deployment should be uninstalled before moving, and re-installed afterward. 

Additional asset files may be freely added, as long as they follow the naming patterns above.
For the additions to be symlinked into the Bash-it directory, the deployment must be (re-)installed.

== Overwriting policy

If the Bash-it framework is already present at `~/.bash-it/`, it is re-used.

The `bash-it` deployment backs up any clashing pre-existing files in the `~/.bash-it` directory.
The backup directory is at `state/backups/bash-it/`.

== Deployment removal notes

The `bash-it` deployment is fully reversible: the retrieved repositories are removed, and the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

The removal does not touch anything in the asset directory.