= Deployment bundle `essentials`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc: macro
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:lsb: [
:rsb: ]

++++
<p align="center">
<em>The deployment bundle for <a href="https://github\.com/no-simpler/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

The deployment bundle `*essentials*` for https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] is a collection of opinionated system set-up scripts.
It is intended as a useful starting point for any machine that runs https://www.gnu.org/software/bash[Bash].

toc::[]

== Description

Once the bundle is fully installed, and the shell reloaded, _voilà_:

* https://sourceforge.net/projects/zsh[Zsh] is the default shell.
* Zsh is supercharged with https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].
* Basic necessities, such as https://git-scm.com[Git], https://www.vim.org[Vim], and https://gnupg.org[GnuPG] are available.
* Both https://ohmyz.sh[oh-my-zsh] and https://github.com/Bash-it/bash-it[Bash-it] frameworks are installed and loaded.
* A minimalistic theme for both shell frameworks is active.
* Opinionated configs are plugged in for Git, Vim, Bash, and Zsh.
* Pre-existing files and installations are safely backed up or re-used.

All of the above is controlled and customized through key configuration files located under the Grail directory at `~/.divine/grail/assets/`.

.Overview of asset directories for the bundle `essentials`
[%noheader,cols="<.<a,<.<a",stripes=none]
|===

| +++<p align="center">+++
`*bash-it*/` *&dagger;*
+++</p>+++

Custom assets for the https://github.com/Bash-it/bash-it[Bash-it] shell framework.

| +++<p align="center">+++
`*brewfile*/` *&dagger;*
+++</p>+++

The https://github.com/Homebrew/homebrew-bundle[Brewfile], maintained on macOS.

| +++<p align="center">+++
`*config-git*/`
+++</p>+++

Global configuration for Git.

| +++<p align="center">+++
`*config-shell*/`
+++</p>+++

Startup scripts (https://en.wikipedia.org/wiki/Run_commands[runcoms]) for Bash and Zsh.

| +++<p align="center">+++
`*config-vim*/`
+++</p>+++

Global configuration for Vim.

| +++<p align="center">+++
`*home-dirs*/` *&dagger;*
+++</p>+++

The file `*home-dirs.cfg*` defines a sub-directory tree to be maintained under the home directory.

| +++<p align="center">+++
`*oh-my-zsh*/` *&dagger;*
+++</p>+++

Custom assets for the https://ohmyz.sh[oh-my-zsh] shell framework.

| +++<p align="center">+++
`*portable-bin*/`
+++</p>+++

Container for the personal executables (this directory is maintained on the `$PATH`)

|===

[.note]
[%noheader,cols="<.<a"]
|===
| The dagger mark (*&dagger;*) meaning: in order for the modifications in that asset directory to take effect, the deployment must be (re-)installed.
|===

Refer to each deployment's section for more information.

== Installing and uninstalling the bundle

=== System requirements

This deployment bundle is for the https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] framework.

=== Installing the bundle

==== Framework already installed

If _Divine.dotfiles_ is already installed, the following Terminal command *attaches* this bundle to the Grail directory:

[source,bash]
----
di attach essentials --yes
----

And this Terminal command *installs* the attached bundle:

[source,bash]
----
di install --bundle essentials --yes
----

==== Installing framework and bundle

The following Terminal command *installs _Divine.dotfiles_ framework and this bundle* in one go and without prompts:

[source,bash]
----
bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/install/insta\
ll.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget \
--version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Erro\
r: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { pr\
intf >&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TM\
P; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && \
exit 3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach essentials --yes \
&& ~/.divine/intervene.sh install --yes
----

[.note]
[%noheader,cols="<.<a"]
|===
| Any pre-existing files on the system are either re-used or backed up.
Upon the uninstallation, such files are restored into their original places.
|===

=== Uninstalling the bundle

==== Keeping framework

The following Terminal command *uninstalls* the bundle:

[source,bash]
----
di remove --bundle essentials --yes
----

And this Terminal command *detaches the bundle* from the Grail directory:

[source,bash]
----
di detach essentials --yes
----

==== Uninstalling framework and bundle

The following command completely *uninstalls this bundle and erases _Divine.dotfiles_ framework without a trace* in one go and without prompts:

[source,bash]
----
~/.divine/intervene.sh remove --yes --obliterate \
&& ~/.divine/intervene.sh detach essentials --yes \
&& bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/uninstall/uni\
nstall.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif w\
get --version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> \
Error: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || \
{ printf >&2 \"\n==> Error: failed to download uninstallation script\n\"; rm -\
f \$TMP; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC\
)) && exit 3 || exit 0" bash --yes --obliterate
----

== Bundled deployments

=== Divinefile

The bundle includes a Divinefile that maintains the following system packages.
Below is the list of the more prominent packages in the Divinefile.
For the full list, refer to the `Divinefile` itself, located in the root of the bundle directory at `state/bundles/no-simpler/divine-bundle-essentials/`.

.Highlights of Divinefile packages for the bundle `essentials`
[%header,cols="^.^1a,<.^2a,<.<3a",stripes=none]
|===

^.^| Priority
^.^| Package name
^.^| Package notes

| `*1000*`
| `git`
|

| `*1000*`
| `vim`
|

| `*1000*`
| `zsh`
|

| `*1000*`
| `wget`
| Except macOS, where it is pre-installed.

| `*1000*`
| `curl`
| Except macOS, where it is pre-installed.

| `*1000*`
| `gnupg`
|

| `*1000*`
| `tree`
|

|===

include::config-shell/README.adoc[leveloffset=2]

include::config-git/README.adoc[leveloffset=2]

include::config-vim/README.adoc[leveloffset=2]

include::portable-bin/README.adoc[leveloffset=2]

include::home-dirs/README.adoc[leveloffset=2]

include::zsh-addons/README.adoc[leveloffset=2]

include::zsh-default/README.adoc[leveloffset=2]

include::brewfile/README.adoc[leveloffset=2]

include::bash-it/README.adoc[leveloffset=2]

include::oh-my-zsh/README.adoc[leveloffset=2]