= Deployment bundle `essentials`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc: macro
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:lsb: [
:rsb: ]

++++
<p align="center">
<em>The deployment bundle for <a href="https://github\.com/no-simpler/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

The deployment bundle `*essentials*` for https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] is a collection of opinionated system set-up scripts.
It is intended as a useful starting point for any machine that runs https://www.gnu.org/software/bash[Bash].

toc::[]

== Description

Once the bundle is fully installed, and the shell reloaded, _voilà_:

* https://sourceforge.net/projects/zsh[Zsh] is the default shell.
* Zsh is supercharged with https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].
* Basic necessities, such as https://git-scm.com[Git], https://www.vim.org[Vim], and https://gnupg.org[GnuPG] are available.
* Both https://ohmyz.sh[oh-my-zsh] and https://github.com/Bash-it/bash-it[Bash-it] frameworks are installed and loaded.
* A minimalistic theme for both shell frameworks is active.
* Opinionated configs are plugged in for Git, Vim, Bash, and Zsh.
* Pre-existing files and installations are safely backed up or re-used.

All of the above is controlled and customized through key configuration files located under the Grail directory at `~/.divine/grail/assets/`.

.Overview of asset directories for the bundle `essentials`
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
`*bash-it*/` *&dagger;*
+++</p>+++

Custom assets for the https://github.com/Bash-it/bash-it[Bash-it] shell framework.

| +++<p align="center">+++
`*brewfile*/` *&dagger;*
+++</p>+++

The https://github.com/Homebrew/homebrew-bundle[Brewfile], maintained on macOS.

| +++<p align="center">+++
`*config-git*/`
+++</p>+++

Global configuration for Git.

| +++<p align="center">+++
`*config-shell*/`
+++</p>+++

Startup scripts (https://en.wikipedia.org/wiki/Run_commands[runcoms]) for Bash and Zsh.

| +++<p align="center">+++
`*config-vim*/`
+++</p>+++

Global configuration for Vim.

| +++<p align="center">+++
`*home-dirs*/` *&dagger;*
+++</p>+++

The file `*home-dirs.cfg*` defines a sub-directory tree to be maintained under the home directory.

| +++<p align="center">+++
`*oh-my-zsh*/` *&dagger;*
+++</p>+++

Custom assets for the https://ohmyz.sh[oh-my-zsh] shell framework.

| +++<p align="center">+++
`*portable-bin*/`
+++</p>+++

Container for the personal executables (this directory is maintained on the `$PATH`)

|===

[.note]
[%noheader,cols="<.<a"]
|===
| The dagger mark (*&dagger;*) meaning: in order for the modifications in that asset directory to take effect, the deployment must be (re-)installed.
|===

Refer to each deployment's section for more information.

== Installing and uninstalling the bundle

=== System requirements

This deployment bundle is for the https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] framework.

=== Installing the bundle

==== Framework already installed

If _Divine.dotfiles_ is already installed, the following Terminal command *attaches* this bundle to the Grail directory:

[source,bash]
----
di attach essentials --yes
----

And this Terminal command *installs* the attached bundle:

[source,bash]
----
di install --bundle essentials --yes
----

==== Installing framework and bundle

The following Terminal command *installs _Divine.dotfiles_ framework and this bundle* in one go and without prompts:

[source,bash]
----
bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/install/insta\
ll.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget \
--version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Erro\
r: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { pr\
intf >&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TM\
P; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && \
exit 3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach essentials --yes \
&& ~/.divine/intervene.sh install --yes
----

[.note]
[%noheader,cols="<.<a"]
|===
| Any pre-existing files on the system are either re-used or backed up.
Upon the uninstallation, such files are restored into their original places.
|===

=== Uninstalling the bundle

==== Keeping framework

The following Terminal command *uninstalls* the bundle:

[source,bash]
----
di remove --bundle essentials --yes
----

And this Terminal command *detaches the bundle* from the Grail directory:

[source,bash]
----
di detach essentials --yes
----

==== Uninstalling framework and bundle

The following command completely *uninstalls this bundle and erases _Divine.dotfiles_ framework without a trace* in one go and without prompts:

[source,bash]
----
~/.divine/intervene.sh remove --yes --obliterate \
&& ~/.divine/intervene.sh detach essentials --yes \
&& bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/uninstall/uni\
nstall.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif w\
get --version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> \
Error: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || \
{ printf >&2 \"\n==> Error: failed to download uninstallation script\n\"; rm -\
f \$TMP; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC\
)) && exit 3 || exit 0" bash --yes --obliterate
----

== Bundled deployments

=== Divinefile

The bundle includes a Divinefile that maintains the following system packages.
Below is the list of the more prominent packages in the Divinefile.
For the full list, refer to the `Divinefile` itself, located in the root of the bundle directory at `state/bundles/no-simpler/divine-bundle-essentials/`.

.Highlights of Divinefile packages for the bundle `essentials`
[%header,cols="^.^1a,<.^2a,<.<3a",stripes=none]
|===

^.^| Priority
^.^| Package name
^.^| Package notes

| `*1000*`
| `git`
|

| `*1000*`
| `vim`
|

| `*1000*`
| `zsh`
|

| `*1000*`
| `wget`
| Except macOS, where it is pre-installed.

| `*1000*`
| `curl`
| Except macOS, where it is pre-installed.

| `*1000*`
| `gnupg`
|

| `*1000*`
| `tree`
|

|===

:leveloffset: 2

= Deployment `config-shell` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-shell` deployment symlinks the configuration files for https://www.gnu.org/software/bash/[Bash] and https://sourceforge.net/projects/zsh[Zsh] into the home directory.

The `config-shell` deployment has the priority of `*333*`.

== Deployment installation notes

The deployment supplants any pre-existing Bash and Zsh configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the `config-shell` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `_<deployment dir>_/*.bashprofile*`
| symlinked
| `~/*.bashprofile*`
.2+| The base runcoms for login shells <<config-shell-login,^1^>>

| `_<deployment dir>_/*.zprofile*`
| symlinked
| `~/*.zprofile*`

| `_<deployment dir>_/*.bashrc*`
| symlinked
| `~/*.bashrc*`
.2+| The base runcoms for interactive shells <<config-shell-interactive,^2^>>

| `_<deployment dir>_/*.zshrc*`
| symlinked
| `~/*.zshrc*`

| `_<asset dir itself>_`
| symlinked
| `~/*.runcoms*/`
| The directory for the user's runcoms <<config-shell-custom,^3^>>

|
| created
| `~/*.hushlogin*`
| The MOTD disabler <<config-shell-hushlogin,^4^>>

|
| created
| `~/*.pre.sh*`
| The box-specific universal runcoms that are sourced _before_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|
| may be created manually by the user
| `~/*.pre.bash*`
| The box-specific Bash runcoms that are sourced _before_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|
| may be created manually by the user
| `~/*.pre.zsh*`
| The box-specific Zsh runcoms that are sourced _before_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|
| created
| `~/*.post.sh*`
| The box-specific universal runcoms that are sourced _after_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|
| may be created manually by the user
| `~/*.post.bash*`
| The box-specific Bash runcoms that are sourced _after_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|
| may be created manually by the user
| `~/*.post.zsh*`
| The box-specific Zsh runcoms that are sourced _after_ the ones in the `~/.runcoms/` directory <<config-shell-box-specific,^5^>>

|===

[.note]
[%noheader,cols="<.<a"]
|===
| The word 'runcom', which is used throughout this readme, is short for the https://en.wikipedia.org/wiki/Run_commands['run commands'].
The runcom is is what the 'rc' stands for in the file names like `.bashrc` or `.zshrc`.

In the context of the `config-shell` deployment, a runcom is a file that contains the shell initialization commands.
|===

== Included assets

The `config-shell` deployment's *asset directory* is located at `grail/assets/config-shell`.

* The base runcoms are kept in the deployment directory because they are not intended for manual modification.
** [[config-shell-login]]The *login shell runcoms* are:
+
--
*** `_<deployment dir>_/*.bash_profile*`
*** `_<deployment dir>_/*.zprofile*`
--
+
These effectively delegate to their <<config-shell-interactive,counterparts>> for interactive shells.
** [[config-shell-interactive]]The *interactive shell runcoms* are:
+
--
*** `_<deployment dir>_/*.bashrc*`
*** `_<deployment dir>_/*.zshrc*`
--
+
These do little on top of sequentially sourcing the <<config-shell-runcoms,custom>> runcoms.
* [[config-shell-runcoms]]The asset directory houses the *custom runcoms*.
+
During the shell startup, both `.bashrc` and `.zshrc` source files from this directory, in the ascending alphanumerical order:
+
--
** The `.bashrc` script sources every `__<name>__**.bash**` and every `__<name>__**.sh**` file.
** The `.zshrc` script sources every `__<name>__**.zsh**` and every `__<name>__**.sh**` file.
--
* [[config-shell-blanks]]A number of empty-ish files are created in the home directory:
** [[config-shell-hushlogin]]`~/*.hushlogin*` — the mere existence of this file in the home directory prevents any sort of textual banner from being printed durint the shell startup.
** [[config-shell-box-specific]]The following runcoms are *box-specific*, meaning they are not intended to leave the current system:
+
--
*** Sourced _before_ the <<config-shell-runcoms,custom>> runcoms:
**** `~/*.pre.bash*` — exclusive to Bash.
**** `~/*.pre.zsh*` — exclusive to Zsh.
**** `~/*.pre.sh*` — universal.
+
This particular runcom is loaded with the definitions of the `D{dus}OS_FAMILY`, `D{dus}OS_DISTRO`, and `D{dus}OS_PKGMGR` variables, which describe the current OS.
*** Sourced _after_ the <<config-shell-runcoms,custom>> runcoms:
**** `~/*.post.bash*` — exclusive to Bash.
**** `~/*.post.zsh*` — exclusive to Zsh.
**** `~/*.post.sh*` — universal.
--
+
The `__<name>__**.bash**` and `__<name>__**.zsh**` runcoms are not created by default, but can be created manually should the need arise.

The following <<config-shell-runcoms,custom>> runcoms are provided with the deployment and contain an opinionated set of startup commands:

* `*00-config.bash*` — the general Bash configuration commands.
* `*00-config.zsh*` — the general Zsh configuration commands.
* `*01-bash-it.bash*` — the commands that initialize the https://github.com/Bash-it/bash-it[Bash-it framework], if it is installed.
* `*01-oh-my-zsh.zsh*` — the commands that initialize the https://ohmyz.sh[oh-my-zsh framework], if it is installed.
* `*02-env.sh*` — the environment variables for both shells, including the modifications of the `$PATH` variable.
* `*03-fixes.sh*` — the bug fixes for both shells.
* `*04-aliases.sh*` — the aliases for both shells.
* `*05-funcs.sh*` — the utility functions for both shells.
* `*06-addons.zsh*` — the commands that initialize the addons for Zsh.

[[config-shell-dependencies]]
== Dependencies

The `config-shell` deployment is stand-alone, but provides the support for other deployments in the current bundle via the included <<config-shell-runcoms,custom>> runcoms:

* `01-bash-it.bash` — initializes the Bash-it framework for the `bash-it` deployment.
* `01-oh-my-zsh.zsh` — initializes the oh-my-zsh framework for the `oh-my-zsh` deployment.
* `02-env.sh` — ensures that all flavors of `bin` directory are on the `$PATH` variable for the `home-dirs` and `portable-bin` deployments.
* `06-addons.zsh` — initializes the Zsh addons for the `zsh-addons` deployment.

== Supported asset modifications

All <<config-shell-runcoms,custom>> runcoms may be freely modified in the asset directory; the modifications will take effect after the shell reload.
Keep in mind, that the modifications to the runcoms that <<config-shell-dependencies,support>> other deployments may break those deployments.

The custom runcoms may be renamed as long as they retain a recognized suffix; however they must remain in the root of the asset directory.
Any number of runcoms may be added to the root of the asset directory; the additional runcoms will take effect after the shell reload.

== Overwriting policy

The `config-shell` deployment backs up any clashing pre-existing files in the home directory.
The backup directory is at `state/backups/config-shell/`.

The <<config-shell-blanks,blank>> files, however, do not overwrite the pre-existing files.

== Deployment removal notes

The `config-shell` deployment is fully reversible: the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `config-git` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-git` deployment symlinks the configuration files for https://git-scm.com[Git] into the home directory.

The `config-git` deployment has the priority of `*333*`.

== Deployment installation notes

The `config-git` deployment supplants any pre-existing Git configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the `config-git` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*.gitconfig*`
| symlinked
| `~/*.gitconfig*`
| The global Git config <<config-git-config,^1^>>

| `*.gitattributes*`
| symlinked
| `~/*.gitattributes*`
| The global Git attributes file <<config-git-attributes,^2^>>

|===

== Included assets

The `config-git` deployment's *asset directory* is located at `grail/assets/config-git`.

The two global configuration files for https://git-scm.com[Git] are provided:

- [[config-git-config]]`*.gitconfig*` — this file is interacted with by the https://git-scm.com/docs/git-config[`git config --global`] command.
- [[config-git-attributes]]`*.gitattributes*` — this file globally influences certain Git operations by https://git-scm.com/docs/gitattributes[assigning attributes] to the certain file path patterns.

A small amount of opinionated configuration is included in the specified files.

== Dependencies

The `config-git` deployment is stand-alone.

The Divinefile included with the current bundle ensures that Git is installed.

== Supported asset modifications

The included configuration files may be freely modified in the asset directory; the modifications will take effect immediately.
Renaming or moving any of the configuration files will break them.

The `config-git` deployment does not support any additional assets.

== Overwriting policy

The `config-git` deployment backs up any clashing pre-existing files in the home directory.
The backup directory is at `state/backups/config-git/`.

== Deployment removal notes

The `config-git` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `config-vim` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-vim` deployment symlinks the configuration and customization files for https://www.vim.org[Vim] into the home directory.

The `config-vim` deployment has the priority of `*333*`.

== Deployment installation notes

The `config-vim` deployment supplants any pre-existing Vim configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the `config-vim` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*.vimrc*`
| symlinked
| `~/*.vimrc*`
| The main Vim config <<config-vim-vimrc,^1^>>

| `*.ideavimrc*`
| symlinked
| `~/*.ideavimrc*`
| The optional IdeaVim config <<config-vim-ideavimrc,^2^>>

| `.vim/**__<name>__**/`
| symlinked
| `~/.vim/**__<name>__**/`
| The Vim customization directories <<config-vim-customization-dirs,^3^>>

|===

== Included assets

The `config-vim` deployment's *asset directory* is located at `grail/assets/config-vim`.

The native configuration files, containing an opinionated set of Vim startup commands:

* [[config-vim-vimrc]]`*.vimrc*` — the primary Vim configuration file.
+
This file includes an installation command for the https://github.com/junegunn/vim-plug[vim-plug] (_a minimalist Vim plugin manager_) along with a number of plugins and settings.
* [[config-vim-ideavimrc]]`*.ideavimrc*` — the configuration file for the https://github.com/JetBrains/ideavim[IdeaVim] (_a Vim emulation plugin for IDEs based on the IntelliJ Platform_).
+
If you don't use any of the IntelliJ products, this file is harmless.

[[config-vim-customization-dirs]]
A number of Vim *customization directories* can be created in the root of the `.vim/` directory, as containers for your customizations.
Most of these directories are not included with the deployment to prevent clutter.
One keymap is provided as an example:

* `*keymap/shifted.vim*` — the 'Caps Lock' mode toggled by double-tapping `j`.

Overall, the following customization directories are supported by Vim:

* `*after/*` — the files to be loaded after the files in `plugin/`.
* `*autoload/*` — the files to be loaded when they are actually needed.
* `*colors/*` — the color schemes.
* `*compiler/*` — the compiler-related options in the current buffer.
* `*doc/*` — the custom plugin documentation.
* `*ftdetect/*` — the file type detection plugins.
* `*ftplugin/*` — the file type exclusive plugins.
* `*indent/*` — the file type exclusive indentation settings.
* `*keymap/*` — the key mapping files.
* `*lang/*` — the language files.
* `*macros/*`
* `*plugin/*` — the standard plugins.
* `*syntax/*` — the syntax highlighting plugins.
* `*tools/*`

Refer to the Vim https://vimhelp.org[help] for more information on the semantics of each directory.

== Dependencies

The `config-vim` deployment is stand-alone.

The Divinefile included with the current bundle ensures that Vim is installed.

== Supported asset modifications

The `.vimrc` and `.ideavim` files may be freely modified in the asset directory; the modifications will take effect on the next Vim startup.
Renaming or moving any of the configuration files will break them.

The `.ideavim` file can be safely removed from the asset directory before installing the deployment.

The symlinked content of the Vim customization directories may be freely modified in the asset directory; the modifications will take effect on the next Vim startup.

The additional customization directories or files may be freely added to the root of the `.vim/` directory.
For the additions to be symlinked into `~/.vim/` directory, the deployment must be (re-)installed.

== Overwriting policy

The `config-vim` deployment backs up any clashing pre-existing files in the home directory.
The backup directory is at `state/backups/config-vim/`.

A pre-existing `~/.vim/` directory is not replaced as a whole, but the files and directories in its root are.

== Deployment removal notes

The `config-git` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `portable-bin` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `portable-bin` deployment uses its own asset directory as a portable container for the personal executables.

The `portable-bin` deployment has the priority of `*500*`.

== Deployment installation notes

Basically, everything dropped into the `portable-bin` deployment's *asset directory* immediately becomes available on `$PATH`.
The portability is achieved when the Grail directory is synchronized across machines (as it is encouraged to be — e.g., using Dropbox or Github).

.Map of asset installation for the `portable-bin` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `_<asset dir itself>_`
| symlinked
| `~/*.pbin*/`
| The portable directory for the personal executables

|===

== Included assets

The `portable-bin` deployment's *asset directory* is located at `grail/assets/portable-bin`.
This drop-box type directory starts empty.

== Dependencies

The `portable-bin` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The `~/.pbin/` directory is put on the `$PATH` variable from the runcom script at `grail/assets/config-shell/02-env.sh`.

== Supported asset modifications

The binaries/executables may be freely dropped into the asset directory.
They will become available on the command line immediately.

== Overwriting policy

The `portable-bin` deployment backs up any clashing pre-existing file at the `~/.pbin` path.
The backup directory is at `state/backups/portable-bin/`.

== Deployment removal notes

The `portable-bin` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `home-dirs` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `home-dirs` deployment maintains a stable tree of personal directories under the home directory.

The `home-dirs` deployment has the priority of `*500*`.

== Deployment installation notes

The `home-dirs` deployment:

* parses the `*home-dirs.cfg*` file (located in the asset directory);
* extracts the relative paths for the current OS;
* ensures that each of those relative paths corresponds to a sub-directory in the home directory.

.Map of asset installation for the `home-dirs` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*home-dirs.cfg*`
| used
| _N/A_
| The manifest of home directories

|===

== Included assets

The `home-dirs` deployment's *asset directory* is located at `grail/assets/home-dirs`.

The `home-dirs.cfg` is a https://github.com/no-simpler/divine-dotfiles#queue-mnf[queue manifest].
It uses the key-value pairs to denote sections or entries that are only relevant for particular OS's.
By default, every entry is relevant everywhere.

A whitespace-separated list of OS's may be provided.
The entire list may be negated by prepenting it with an exclamation mark (`!`).

A key-value that appears on a line of its own comes into effect for the remainder of the manifest, or until overridden.
A key-value on the same line with an entry affects only that entry.

[source]
----
(os: debian)        relative/path/to/directory1   # Debian only
(os: macos bsd)     relative/path/to/directory2   # macOS/BSD only
(os: ! wsl cygwin)  relative/path/to/directory3   # Everything except WSL or Cygwin
(os: all)           relative/path/to/directory4   # 'all'/'any' are reserved values that denote any OS
----

[.note]
[%noheader,cols="<.<a"]
|===
| Refer to the framework https://github.com/no-simpler/divine-dotfiles[documentation] for more information on the queue manifest syntax.
|===

== Dependencies

The `home-dirs` deployment is stand-alone.

== Supported asset modifications

The directory manifest may be freely modified in the asset directory.
For the changes to take effect, the deployment must be (re-)installed.
Renaming or moving the manifest will break it.

== Overwriting policy

The `home-dirs` deployment does not touch any pre-existing files/directories at the desired paths.

== Deployment removal notes

The `home-dirs` deployment takes _extra_ care with removing directories.
The user is prompted before removing any non-empty directory.
The prompt is not affected by the intervention options and always appears.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `zsh-addons` (`1000`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-addons` deployment retrieves a number of community addons for Zsh: https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].

The `zsh-addons` deployment has the priority of `*1000*`.

== Deployment installation notes

The `zsh-addons` deployment clones or downloads the https://github.com/zsh-users[`zsh-users`] Github repositories into the `~/.zsh/` directory:

.Map of asset installation for the `bash-it` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| https://github.com/zsh-users/zsh-completions[`zsh-users/zsh-completions`]
| cloned
| `~/.zsh/zsh-users/**zsh-completions**/`
|

| https://github.com/zsh-users/zsh-syntax-highlighting[`zsh-users/zsh-syntax-highlighting`]
| cloned
| `~/.zsh/zsh-users/**zsh-syntax-highlighting**/`
|

| https://github.com/zsh-users/zsh-autosuggestions[`zsh-users/zsh-autosuggestions`]
| cloned
| `~/.zsh/zsh-users/**zsh-autosuggestions**/`
|

|===

== Included assets

The `zsh-addons` deployment does not use the asset directory.

== Dependencies

The `zsh-addons` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The retrieved addons are initialized from the runcom script at `grail/assets/config-shell/06-addons.zsh`.

== Supported asset modifications

The `zsh-addons` deployment provides no modifiable assets.

== Overwriting policy

The `zsh-addons` deployment backs up any clashing pre-existing files in the `~/.zsh` directory.
The backup directory is at `state/backups/zsh-addons/`.

== Deployment removal notes

The `zsh-addons` deployment is fully reversible: the retrieved repositories are removed, and the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

:leveloffset!:

:leveloffset: 2

= Deployment `zsh-default` (`1333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-default` deployment ensures that https://sourceforge.net/projects/zsh[Zsh] is the default shell for the current OS user.

The `zsh-default` deployment has the priority of `*1333*`.

== Deployment installation notes

After some preparations (involving the `/etc/shells` file), the `zsh-default` deployment calls the `chsh -s _<path to zsh>_` command to change the default shell.
Note that *changing the default shell requires the user's password*.
The password prompt will appear during the installation/removal.

== Included assets

The `zsh-default` deployment does not use the asset directory.

== Dependencies

The `zsh-default` deployment is stand-alone.

On some systems, the Divinefile included with the current bundle ensures that the `chsh` utility is installed.

== Supported asset modifications

The `zsh-default` deployment provides no modifiable assets.

== Overwriting policy

The `zsh-default` deployment does not overwrite any files.

If the default shell is already Zsh, this deployment does nothing.

== Deployment removal notes

The `config-git` deployment is fully reversible: the original default shell is restored.
If the default shell is not changed during the installation, it is not changed during the removal as well.

:leveloffset!:

:leveloffset: 2

= Deployment `brewfile` (`3000!`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `brewfile` deployment maintains a set of system dependencies on macOS using the https://github.com/Homebrew/homebrew-bundle[Brewfile].

The `brewfile` deployment is flagged as dangerous for two reasons:

* Checking whether a Brewfile is installed or not is not reliable.
* Uninstalling a Brewfile is not implemented on Homebrew's side, and this deployment's implementation is an approximation.

As a result of the flag, the `brewfile` deployment is not processed by the intervention utility, unless the `--with-!` option is given.

The `brewfile` deployment has the priority of `*3000*`.

== Deployment installation notes

The `brewfile` deployment delegates to the https://brew.sh/[`brew` utility] to install whatever items are listed in the provided Brewfile.

.Map of asset installation for the `brewfile` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*Brewfile*`
| used
| https://brew.sh/[`brew` utility]
| The manifest of system dependencies

|===

== Included assets

The `brewfile` deployment's *asset directory* is located at `grail/assets/brewfile`.

The included `*Brewfile*` starts up empty, and as such does nothing.
The fundamental dependencies of the current bundle are handled by the included Divinefile.
In other words, the Brewfile is kind of scoffed on around here.

== Dependencies

The `brewfile` deployment is stand-alone.

On macOS, the _Divine.dotfiles_ framework itself ensures that https://brew.sh/[Homebrew] is installed.

== Supported asset modifications

The Brewfile may be freely modified in the asset directory.
For the changes to take effect, the deployment must be (re-)installed.
Renaming or moving the Brewfile will break the deployment.

== Overwriting policy

The handling of Brewfiles is intirely in Homebrew's hands.
Still, no major clobbering is expected.

== Deployment removal notes

Uninstalling a Brewfile is currently not supported by Homebrew.

The `brewfile` deployment provides a workaround.
Upon removal of this deployment, the Brewfile is read in reverse order: for every supported line, the appropriate Homebrew uninstallation command is called.
This procedure is _not_ an exact reverse of the installation due to the possible transient dependencies, as well as other factors.

Currently, the removal of the following Brewfile lines is supported:

* `tap _<name>_` — taps will be untapped.
* `cask _<name>_` — casks will be uninstalled.
* `brew _<name>_` — bottles will be uninstalled.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `bash-it` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `bash-it` deployment introduces the https://github.com/Bash-it/bash-it[Bash-it framework] and custom assets for it into the home directory.

The `bash-it` deployment has the priority of `*3333*`.

== Deployment installation notes

The `bash-it` deployment clones or downloads the https://github.com/Bash-it/bash-it[`Bash-it/bash-it`] repository into the `~/.bash-it/` directory.
Having succeeded, it symlinks additional assets into the framework.

.Map of asset installation for the `bash-it` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| https://github.com/Bash-it/bash-it[Bash-it repo]
| cloned
| `~/**.bash-it**/`
| Bash-it framework <<bash-it-fmwk,^1^>>

| `aliases/**__<name>__.aliases.bash**`
| symlinked
| `~/.bash-it/aliases/available/**__<name>__.aliases.bash**`
| Custom Bash aliases <<bash-it-blanks,^2^>>

| `completion/**__<name>__.completion.bash**`
| symlinked
| `~/.bash-it/completion/available/**__<name>__.completion.bash**`
| Custom Bash completions <<bash-it-blanks,^2^>>

| `lib/**__<name>__.bash**`
| symlinked
| `~/.bash-it/lib/**__<name>__.bash**`
| Custom Bash-it lib scripts <<bash-it-blanks,^2^>>

| `plugins/**__<name>__.plugin.bash**`
| symlinked
| `~/.bash-it/plugins/available/**__<name>__.plugin.bash**`
| Custom Bash-it plugins <<bash-it-blanks,^2^>>

| `themes/**__<name>__**/__<name>__.theme.bash`
| symlinked
| `~/.bash-it/themes/**__<name>__**/`
| Custom Bash-it themes <<bash-it-themes,^3^>>

|===

The path components in bold designate the source and the target of cloning/symlinking.

[[bash-it-fmwk]]
The Bash-it framework is installed with its included installation script.
The `--no-modify-config` option is added because the current bundle already includes the necessary initialization commands.

== Included assets

The `bash-it` deployment's *asset directory* is located at `grail/assets/bash-it`.

[[bash-it-blanks]]
Blank sample files are provided for each kind of custom assets:

- `*aliases/divine.aliases.bash*`
- `*completion/divine.completion.bash*`
- `*lib/divine.bash*`
- `*plugins/divine.plugin.bash*`

[[bash-it-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare/laidbare.theme.bash*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `bash-it` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The retrieved Bash-it framework is initialized from the runcom script at `grail/assets/config-shell/01-bash-it.bash`.
The same file may and should be used to customize the Bash-it framework's loadout.

== Supported asset modifications

All symlinked assets may be freely modified in the asset directory; the modifications will take effect after the shell reload.

However, moving any of the assets will break them.
The deployment should be uninstalled before moving, and re-installed afterward.

Additional asset files may be freely added, as long as they follow the naming patterns above.
For the additions to be symlinked into the Bash-it directory, the deployment must be (re-)installed.

== Overwriting policy

If the Bash-it framework is already present at `~/.bash-it/`, it is re-used.

The `bash-it` deployment backs up any clashing pre-existing files in the `~/.bash-it` directory.
The backup directory is at `state/backups/bash-it/`.

== Deployment removal notes

The `bash-it` deployment is fully reversible: the retrieved repositories are removed, and the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

The removal does not touch anything in the asset directory.

:leveloffset!:

:leveloffset: 2

= Deployment `oh-my-zsh` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Actually fix description table in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `oh-my-zsh` deployment introduces the https://ohmyz.sh[oh-my-zsh framework] and custom assets for it into the home directory.

The `oh-my-zsh` deployment has the priority of `*3333*`.

== Deployment installation notes

The `oh-my-zsh` deployment clones or downloads the https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`] repository into the `~/.oh-my-zsh/` directory.
Having succeeded, it symlinks additional assets into the framework.

.Map of asset installation for the `oh-my-zsh` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| https://github.com/robbyrussell/oh-my-zsh[oh-my-zsh repo]
| cloned
| `~/**.oh-my-zsh**/`
| oh-my-zsh framework <<oh-my-zsh-fmwk,^1^>>

| `plugins/**__<name>__**/__<name>__.plugin.zsh`
| symlinked
| `~/.oh-my-zsh/custom/plugins/**__<name>__**/`
| Custom oh-my-zsh plugins <<oh-my-zsh-plugins,^2^>>

| `themes/**__<name>__.zsh-theme**`
| symlinked
| `~/.oh-my-zsh/custom/themes/**__<name>__.zsh-theme**`
| Custom oh-my-zsh themes <<oh-my-zsh-themes,^3^>>

|===

The path components in bold designate the source and the target of cloning/symlinking.

[[oh-my-zsh-fmwk]]
The oh-my-zsh framework is installed by cloning its https://github.com/robbyrussell/oh-my-zsh[Github repository].
The included installation script (which normally adds initialization commands to the `~/.zshrc` runcom) is not executed, because the current bundle already includes necessary initialization commands.

== Included assets

The `oh-my-zsh` deployment's *asset directory* is located at `grail/assets/oh-my-zsh`.

[[oh-my-zsh-plugins]]
A blank example file is provided for the custom plugins:

- `*plugins/divine/divine.plugin.zsh*`

[[oh-my-zsh-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare.zsh-theme*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `oh-my-zsh` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The retrieved oh-my-zsh framework is initialized from the runcom script at `grail/assets/config-shell/01-oh-my-zsh.zsh`.
The same file may and should be used to customize the oh-my-zsh framework's loadout.

== Supported asset modifications

All symlinked assets may be freely modified in the asset directory; the modifications will take effect after the shell reload.

However, moving any of the assets will break them.
The deployment should be uninstalled before moving, and re-installed afterward.

Additional asset files may be freely added, as long as they follow the naming patterns above.
For the additions to be symlinked into the oh-my-zsh directory, the deployment must be (re-)installed.

== Overwriting policy

If the oh-my-zsh framework is already present at `~/.oh-my-zsh/`, it is re-used.

The `oh-my-zsh` deployment backs up any clashing pre-existing files in the `~/.oh-my-zsh` directory.
The backup directory is at `state/backups/oh-my-zsh/`.

== Deployment removal notes

The `oh-my-zsh` deployment is fully reversible: the retrieved repositories are removed, and the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

The removal does not touch anything in the asset directory.

:leveloffset!: