= Deployment bundle `essentials`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.14
:revremark: Systematize readme for config-shell
:doctype: article
// Visual
:toc: macro
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:lsb: [
:rsb: ]

++++
<p align="center">
<em>A deployment bundle for <a href="https://github\.com/no-simpler/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

The deployment bundle `*essentials*` for https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] is a collection of opinionated system set-up scripts.
It is intended as a useful starting point for any https://en.wikipedia.org/wiki/Unix-like[Unix-like] box.

[horizontal]
Bundle name:: `essentials`
<<dpls-main,Deployments>>:: 10
<<dpls-dfls,Divinefile>> entries:: 9
<<inun-inst-bundle,Attached>> bundle location:: `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials`

toc::[]

[[bundle-main]]
== Description

Once the bundle is fully <<inun-inst,installed>>, and the shell reloaded, _voilà_:

* https://sourceforge.net/projects/zsh[Zsh] is the default shell.
* Zsh is augmented with https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].
* Basic necessities, such as https://git-scm.com[Git], https://www.vim.org[Vim], and https://gnupg.org[GnuPG] are available.
* Both https://ohmyz.sh[oh-my-zsh] and https://github.com/Bash-it/bash-it[Bash-it] frameworks are installed and loaded.
* A minimalistic theme for both shell frameworks is active.
* Opinionated configs are plugged in for Git, Vim, Bash, and Zsh.
* Any pre-existing files that have gotten in the way are safely backed up or re-used.

All of the above is controlled and customized through the key configuration files, which are located at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/`.

.Overview of asset directories for the bundle `essentials`
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*bash-it*/` *&dagger;*
+++</p>+++

Custom assets for the https://github.com/Bash-it/bash-it[Bash-it] shell framework.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*brewfile*/` *&dagger;*
+++</p>+++

The https://github.com/Homebrew/homebrew-bundle[Brewfile], maintained on macOS.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-git*/`
+++</p>+++

The global configuration for Git.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-shell*/`
+++</p>+++

The startup scripts (https://en.wikipedia.org/wiki/Run_commands[runcoms]) for Bash and Zsh.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-vim*/`
+++</p>+++

The global configuration for Vim.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*home-dirs*/` *&dagger;*
+++</p>+++

The file `*home-dirs.cfg*` defines a sub-directory tree to be maintained under the home directory.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*oh-my-zsh*/` *&dagger;*
+++</p>+++

Custom assets for the https://ohmyz.sh[oh-my-zsh] shell framework.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*portable-bin*/`
+++</p>+++

The container for the personal executables (this directory is maintained on the `$PATH`).

|===

[.note]
[%noheader,cols="<.<a"]
|===
| The dagger mark (*&dagger;*) meaning: in order for the modifications in that asset directory to take effect, the deployment must be (re-)installed.
|===

[[inun-main]]
== Installing and uninstalling the bundle

The bundle `essentials` requires the https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] framework.
The (un)installation guide assumes that _Divine.dotfiles_ is installed into the default path: `~/.divine/`, and that the shortcut command `di` is available.

[[inun-inst]]
=== Installing the bundle

[[inun-inst-bundle]]
==== Framework already installed

If _Divine.dotfiles_ is already installed, the following Terminal command *attaches* the bundle `essentials` to the https://github.com/no-simpler/divine-dotfiles#fmwk-grail[Grail directory]:

[source,bash]
----
di attach essentials
----

And this Terminal command *installs* the attached bundle:

[source,bash]
----
di install --bundle essentials
----

[[inun-inst-both]]
==== Installing framework and bundle

The following Terminal command *installs both the _Divine.dotfiles_ framework and the bundle* `*essentials*` in one go and without prompts:

[source,bash]
----
bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/install/insta\
ll.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget \
--version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Erro\
r: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { pr\
intf >&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TM\
P; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && \
exit 3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach essentials --yes \
&& ~/.divine/intervene.sh install --yes
----

[.note]
[%noheader,cols="<.<a"]
|===
| Any pre-existing files that get in the way are either re-used or backed up.
Upon the uninstallation, such files are restored into their original places.
|===

[[inun-uninst]]
=== Uninstalling the bundle

[[inun-uninst-bundle]]
==== Keeping framework

The following Terminal command *uninstalls* the bundle `essentials`:

[source,bash]
----
di remove --bundle essentials
----

And this Terminal command *detaches the bundle* from the https://github.com/no-simpler/divine-dotfiles#fmwk-grail[Grail directory]:

[source,bash]
----
di detach essentials
----

[[inun-uninst-both]]
==== Uninstalling framework and bundle

The following command *uninstalls both the bundle* `*essentials*` *and the _Divine.dotfiles_ framework* in one go and without prompts or backups:

[source,bash]
----
~/.divine/intervene.sh remove --yes --obliterate \
&& ~/.divine/intervene.sh detach essentials --yes \
&& bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/uninstall/uni\
nstall.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif w\
get --version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> \
Error: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || \
{ printf >&2 \"\n==> Error: failed to download uninstallation script\n\"; rm -\
f \$TMP; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC\
)) && exit 3 || exit 0" bash --yes --obliterate
----

[[dpls-main]]
== Bundled deployments

[[dpls-dfls]]
=== Divinefile

The bundle `essentials` includes a https://github.com/no-simpler/divine-dotfiles#dfls-main[Divinefile] that maintains the following system packages.
Below is the list of the more prominent packages in the Divinefile.
For the full list, refer to the `Divinefile` itself, located in the root of the attached bundle's directory at:

[source]
----
https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/Divinefile
----

.Highlights of Divinefile packages for the bundle `essentials`
[%header,cols="^.^1a,<.^2a,<.<3a",stripes=none]
|===

^.^| Priority
^.^| Package name
^.^| Package notes

| `*1000*`
| `git`
|

| `*1000*`
| `vim`
|

| `*1000*`
| `zsh`
|

| `*1000*`
| `wget`
| Except macOS, where it is pre-installed.

| `*1000*`
| `curl`
| Except macOS, where it is pre-installed.

| `*1000*`
| `gnupg`
|

| `*1000*`
| `tree`
|

|===

include::config-shell/README.adoc[leveloffset=2]

include::config-git/README.adoc[leveloffset=2]

include::config-vim/README.adoc[leveloffset=2]

include::portable-bin/README.adoc[leveloffset=2]

include::home-dirs/README.adoc[leveloffset=2]

include::zsh-addons/README.adoc[leveloffset=2]

include::zsh-default/README.adoc[leveloffset=2]

include::brewfile/README.adoc[leveloffset=2]

include::bash-it/README.adoc[leveloffset=2]

include::oh-my-zsh/README.adoc[leveloffset=2]