= Deployment bundle `essentials`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc: macro
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:lsb: [
:rsb: ]

++++
<p align="center">
<em>A deployment bundle for <a href="https://github.com/no-simpler/divine-dotfiles">Divine.dotfiles</a></em>
</p>
++++

The deployment bundle `*essentials*` for https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] is a collection of opinionated system set-up scripts.
It is intended as a useful starting point for any https://en.wikipedia.org/wiki/Unix-like[Unix-like] box.

[horizontal]
Bundle name:: `essentials`
<<dpls-main,Deployments>>:: 10
<<dpls-dfls,Divinefile>> entries:: 9
<<inun-inst-bundle,Attached>> bundle location:: `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials`

toc::[]

[[bundle-main]]
== Description

Once the bundle is fully <<inun-inst,installed>>, and the shell reloaded, _voilà_:

* https://sourceforge.net/projects/zsh[Zsh] is the default shell.
* Zsh is augmented with https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].
* Basic necessities, such as https://git-scm.com[Git], https://www.vim.org[Vim], and https://gnupg.org[GnuPG] are available.
* Both https://ohmyz.sh[oh-my-zsh] and https://github.com/Bash-it/bash-it[Bash-it] frameworks are installed and loaded.
* A minimalistic theme for both shell frameworks is active.
* Opinionated configs are plugged in for Git, Vim, Bash, and Zsh.
* Any pre-existing files that have gotten in the way are safely backed up or re-used.

All of the above is controlled and customized through the key configuration files, which are located at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/`.

.Overview of asset directories for the bundle `essentials`
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*bash-it*/` *&dagger;*
+++</p>+++

Custom assets for the https://github.com/Bash-it/bash-it[Bash-it] shell framework.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*brewfile*/` *&dagger;*
+++</p>+++

The https://github.com/Homebrew/homebrew-bundle[Brewfile], maintained on macOS.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-git*/`
+++</p>+++

The global configuration for Git.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-shell*/`
+++</p>+++

The startup scripts (https://en.wikipedia.org/wiki/Run_commands[runcoms]) for Bash and Zsh.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*config-vim*/`
+++</p>+++

The global configuration for Vim.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*home-dirs*/` *&dagger;*
+++</p>+++

The file `*home-dirs.cfg*` defines a sub-directory tree to be maintained under the home directory.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*oh-my-zsh*/` *&dagger;*
+++</p>+++

Custom assets for the https://ohmyz.sh[oh-my-zsh] shell framework.

| +++<p align="center">+++
`https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/*portable-bin*/`
+++</p>+++

The container for the personal executables (this directory is maintained on the `$PATH`).

|===

[.note]
[%noheader,cols="<.<a"]
|===
| The dagger mark (*&dagger;*) meaning: in order for the modifications in that asset directory to take effect, the deployment must be (re-)installed.
|===

[[inun-main]]
== Installing and uninstalling the bundle

The bundle `essentials` requires the https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] framework.
The (un)installation guide assumes that _Divine.dotfiles_ is installed into the default path: `~/.divine/`, and that the shortcut command `di` is available.

[[inun-inst]]
=== Installing the bundle

[[inun-inst-bundle]]
==== Framework already installed

If _Divine.dotfiles_ is already installed, the following Terminal command *attaches* the bundle `essentials` to the https://github.com/no-simpler/divine-dotfiles#fmwk-grail[Grail directory]:

[source,bash]
----
di attach essentials
----

And this Terminal command *installs* the attached bundle:

[source,bash]
----
di install --bundle essentials
----

[[inun-inst-both]]
==== Installing framework and bundle

The following Terminal command *installs both the _Divine.dotfiles_ framework and the bundle* `*essentials*` in one go and without prompts:

[source,bash]
----
bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/install/insta\
ll.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif wget \
--version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> Erro\
r: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || { pr\
intf >&2 \"\n==> Error: failed to download installation script\n\"; rm -f \$TM\
P; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC)) && \
exit 3 || exit 0" bash --yes \
&& ~/.divine/intervene.sh attach essentials --yes \
&& ~/.divine/intervene.sh install --yes
----

[.note]
[%noheader,cols="<.<a"]
|===
| Any pre-existing files that get in the way are either re-used or backed up.
Upon the uninstallation, such files are restored into their original places.
|===

[[inun-uninst]]
=== Uninstalling the bundle

[[inun-uninst-bundle]]
==== Keeping framework

The following Terminal command *uninstalls* the bundle `essentials`:

[source,bash]
----
di remove --bundle essentials
----

And this Terminal command *detaches the bundle* from the https://github.com/no-simpler/divine-dotfiles#fmwk-grail[Grail directory]:

[source,bash]
----
di detach essentials
----

[[inun-uninst-both]]
==== Uninstalling framework and bundle

The following command *uninstalls both the bundle* `*essentials*` *and the _Divine.dotfiles_ framework* in one go and without prompts or backups:

[source,bash]
----
~/.divine/intervene.sh remove --yes --obliterate \
&& ~/.divine/intervene.sh detach essentials --yes \
&& bash -c "TMP=\$(mktemp); \
URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/uninstall/uni\
nstall.sh; if curl --version &>/dev/null; then curl -fsSL \$URL >\$TMP; elif w\
get --version &>/dev/null; then wget -qO \$TMP \$URL; else printf >&2 \"\n==> \
Error: failed to detect neither curl nor wget\n\"; rm -f \$TMP; exit 1; fi || \
{ printf >&2 \"\n==> Error: failed to download uninstallation script\n\"; rm -\
f \$TMP; exit 2; }; chmod +x \$TMP && \$TMP \"\$@\"; RC=\$?; rm -f \$TMP; ((RC\
)) && exit 3 || exit 0" bash --yes --obliterate
----

[[dpls-main]]
== Bundled deployments

[[dpls-dfls]]
=== Divinefile

The bundle `essentials` includes a https://github.com/no-simpler/divine-dotfiles#dfls-main[Divinefile] that maintains the following system packages.
Below is the list of the more prominent packages in the Divinefile.
The `Divinefile` itself provides the full list.
It is located in the root of the attached bundle's directory at:

[none]
* `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/Divinefile`

.Highlights of Divinefile packages for the bundle `essentials`
[%header,cols="^.^1a,<.^2a,<.<3a",stripes=none]
|===

^.^| Priority
^.^| Package name
^.^| Package notes

| `*1000*`
| `git`
|

| `*1000*`
| `vim`
|

| `*1000*`
| `zsh`
|

| `*1000*`
| `wget`
| Except macOS, where it is pre-installed.

| `*1000*`
| `curl`
| Except macOS, where it is pre-installed.

| `*1000*`
| `gnupg`
|

| `*1000*`
| `tree`
|

|===

:leveloffset: 2

[[config-shell-main]]
= Deployment `config-shell` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-shell` deployment symlinks the configuration files (https://en.wikipedia.org/wiki/Run_commands['runcoms']) for https://www.gnu.org/software/bash/[Bash] and https://sourceforge.net/projects/zsh[Zsh] into the home directory.

[[config-shell-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `config-shell`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/config-shell/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-shell/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/config-shell/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `config-shell` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<config-shell-mtdt,_<dpl-dir>_>>/*.bashprofile*`
! =>
! `~/*.bashprofile*`
.4+! <<config-shell-base,^1^>>

! `<<config-shell-mtdt,_<dpl-dir>_>>/*.zprofile*`
! =>
! `~/*.zprofile*`

! `<<config-shell-mtdt,_<dpl-dir>_>>/*.bashrc*`
! =>
! `~/*.bashrc*`

! `<<config-shell-mtdt,_<dpl-dir>_>>/*.zshrc*`
! =>
! `~/*.zshrc*`

! `<<config-shell-mtdt,*_<asset-dir>_*>>/`
! =>
! `~/*.runcoms*/`
! <<config-shell-runcoms,^2^>> <<config-shell-included,^5^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

| +++<p align="center">+++
*Creating*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

!
! =>
! `~/*.pre.bash*`
.6+! <<config-shell-box-specific,^3^>>

!
! =>
! `~/*.pre.zsh*`

!
! =>
! `~/*.pre.sh*`

!
! =>
! `~/*.post.bash*`

!
! =>
! `~/*.post.zsh*`

!
! =>
! `~/*.post.sh*`

!
! =>
! `~/*.hushlogin*`
! <<config-shell-hushlogin,^4^>>

!===

Installation:: Created, or re-used if pre-existing.
Removal:: Removed, or untouched if re-used.

|===

== Included assets

* [[config-shell-base]]The *base runcoms* (the `.*profile` and `.*rc` files recognized by Bash and Zsh) are kept in the deployment directory because they are not intended for manual modification.
+
These do little on top of sequentially sourcing the <<config-shell-runcoms,custom>> and <<config-shell-box-specific,box-specific>> runcoms.
* [[config-shell-runcoms]]The <<config-shell-mtdt,asset directory>> is home for the *custom runcoms*.
+
During the shell startup, both `.bashrc` and `.zshrc` source files from this directory, in the ascending alphanumerical order:
+
--
** The `.bashrc` script sources every `__<name>__**.bash**` and every `__<name>__**.sh**` file.
** The `.zshrc` script sources every `__<name>__**.zsh**` and every `__<name>__**.sh**` file.
--
+
A sample set of opinionated runcoms is <<config-shell-included,included>>.
* [[config-shell-box-specific]]The empty-ish *box-specific runcoms* are created in the home directory, and are not intended to leave the current machine:
+
--
** Sourced _before_ the <<config-shell-runcoms,custom>> runcoms:
*** `~/*.pre.bash*` — exclusive to Bash.
*** `~/*.pre.zsh*` — exclusive to Zsh.
*** `~/*.pre.sh*` — universal.
+
This particular runcom is pre-loaded with the definitions of the https://github.com/no-simpler/divine-dotfiles#indct-os-family[`D{dus}OS_FAMILY`], https://github.com/no-simpler/divine-dotfiles#indct-os-distro[`D{dus}OS_DISTRO`], and https://github.com/no-simpler/divine-dotfiles#indct-os-pkgmgr[`D{dus}OS_PKGMGR`] variables, which describe the current OS.
** Sourced _after_ the <<config-shell-runcoms,custom>> runcoms:
*** `~/*.post.bash*` — exclusive to Bash.
*** `~/*.post.zsh*` — exclusive to Zsh.
*** `~/*.post.sh*` — universal.
--
* [[config-shell-hushlogin]]`~/*.hushlogin*` — the presence of this file in the home directory prevents any sort of textual banner from being printed durint the shell startup.

[[config-shell-included]]
The following <<config-shell-runcoms,custom>> runcoms are provided with the deployment and contain an opinionated set of startup commands:

* `*00-config.bash*` — the general Bash configuration commands.
* `*00-config.zsh*` — the general Zsh configuration commands.
* `*01-bash-it.bash*` — the commands that initialize the https://github.com/Bash-it/bash-it[Bash-it framework], if it is <<bash-it-main,installed>>.
* `*01-oh-my-zsh.zsh*` — the commands that initialize the https://ohmyz.sh[oh-my-zsh framework], if it is <<oh-my-zsh-main,installed>>.
* `*02-env.sh*` — the environment variables for both shells, including the modifications of the `$PATH` variable.
* `*03-fixes.sh*` — the bug fixes for both shells.
* `*04-aliases.sh*` — the aliases for both shells.
* `*05-funcs.sh*` — the utility functions for both shells.
* `*06-addons.zsh*` — the commands that initialize the addons for Zsh.

[[config-shell-dependencies]]
== Dependencies

The `config-shell` deployment is stand-alone.

However, it provides the support for other deployments in the current bundle (via the <<config-shell-included,included>> custom runcoms):

* `01-bash-it.bash` — initializes the Bash-it framework for the <<bash-it-main,`bash-it`>> deployment.
* `01-oh-my-zsh.zsh` — initializes the oh-my-zsh framework for the <<oh-my-zsh-main,`oh-my-zsh`>> deployment.
* `02-env.sh` — ensures that all flavors of `bin` directory are on the `$PATH` variable for the <<home-dirs-main,`home-dirs`>> and <<portable-bin-main,`portable-bin`>> deployments.
* `06-addons.zsh` — initializes the Zsh addons for the <<zsh-addons-main,`zsh-addons`>> deployment.

:leveloffset!:

:leveloffset: 2

[[config-git-main]]
= Deployment `config-git` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-git` deployment symlinks the configuration files for https://git-scm.com[Git] into the home directory.

[[config-git-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `config-git`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/config-git/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-git/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/config-git/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `config-git` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<config-git-mtdt,_<asset-dir>_>>/*.gitconfig*`
! =>
! `~/*.gitconfig*`
! <<config-git-gc,^1^>>

! `<<config-git-mtdt,_<asset-dir>_>>/*.gitattributes*`
! =>
! `~/*.gitattributes*`
! <<config-git-ga,^2^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

== Included assets

[[config-git-gc]][[config-git-ga]]The two global configuration files for https://git-scm.com[Git] are provided:

- `*.gitconfig*` — this file is interacted with by the https://git-scm.com/docs/git-config[`git config --global`] command.
- `*.gitattributes*` — this file globally influences certain Git operations by https://git-scm.com/docs/gitattributes[assigning attributes] to the certain file path patterns.

A small amount of opinionated configuration is included in the specified files.

== Dependencies

The `config-git` deployment is stand-alone.

The <<dpls-dfls,Divinefile>> included with the current bundle ensures that Git is installed.

:leveloffset!:

:leveloffset: 2

[[config-vim-main]]
= Deployment `config-vim` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-vim` deployment symlinks the configuration and customization files for https://www.vim.org[Vim] into the home directory.

[[config-vim-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `config-vim`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/config-vim/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-vim/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/config-vim/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `config-vim` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<config-vim-mtdt,_<asset-dir>_>>/*.vimrc*`
! =>
! `~/*.vimrc*`
! <<config-vim-rc,^1^>>

! `<<config-vim-mtdt,_<asset-dir>_>>/*.ideavimrc*`
! =>
! `~/*.ideavimrc*`
! <<config-vim-idearc,^2^>>

! `<<config-vim-mtdt,_<asset-dir>_>>/.vim/**__<name>__**/`
! =>
! `~/.vim/**__<name>__**/`
! <<config-vim-dirs,^3^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

== Included assets

The native configuration files, containing an opinionated set of Vim startup commands:

* [[config-vim-rc]]`*.vimrc*` — the primary Vim configuration file.
+
This file includes an installation command for the https://github.com/junegunn/vim-plug[vim-plug] (_a minimalist Vim plugin manager_) along with some plugins and settings.
* [[config-vim-idearc]]`*.ideavimrc*` — the configuration file for the https://github.com/JetBrains/ideavim[IdeaVim] (_a Vim emulation plugin for IDEs based on the IntelliJ Platform_).
+
If you don't use any of the IntelliJ products, this file is harmless.

[[config-vim-dirs]]
A number of Vim *customization directories* can be created in the root of the `.vim/` directory, as containers for your customizations.
One keymap is provided as an example:

* `*keymap/shifted.vim*` — the 'Caps Lock' mode toggled by double-tapping `j`.

Overall, the following customization directories are supported by Vim:

* `*after/*` — the files to be loaded after the files in `plugin/`.
* `*autoload/*` — the files to be loaded when they are actually needed.
* `*colors/*` — the color schemes.
* `*compiler/*` — the compiler-related options in the current buffer.
* `*doc/*` — the custom plugin documentation.
* `*ftdetect/*` — the file type detection plugins.
* `*ftplugin/*` — the file type exclusive plugins.
* `*indent/*` — the file type exclusive indentation settings.
* `*keymap/*` — the key mapping files.
* `*lang/*` — the language files.
* `*macros/*`
* `*plugin/*` — the standard plugins.
* `*syntax/*` — the syntax highlighting plugins.
* `*tools/*`

The Vim https://vimhelp.org[help] provides more information on the semantics of each directory.

== Dependencies

The `config-vim` deployment is stand-alone.

The <<dpls-dfls,Divinefile>> included with the current bundle ensures that Vim is installed.

:leveloffset!:

:leveloffset: 2

[[portable-bin-main]]
= Deployment `portable-bin` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `portable-bin` deployment uses its own asset directory as a portable container for the personal executables.

[[portable-bin-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `portable-bin`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `500`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/portable-bin/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/portable-bin/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/portable-bin/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `portable-bin` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<portable-bin-mtdt,_<asset-dir>_>>/`
! =>
! `~/*.pbin*/`
!

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

== Included assets

Everything dropped into the `portable-bin` deployment's *asset directory* immediately becomes available on `$PATH`.
The portability is achieved when the Grail directory is synchronized across machines (as it is encouraged to be — e.g., using Dropbox or Github).
The included asset directory starts out empty.

== Dependencies

The `portable-bin` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The `~/.pbin/` directory is put on the `$PATH` variable from the runcom script at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-shell/02-env.sh`.

:leveloffset!:

:leveloffset: 2

[[home-dirs-main]]
= Deployment `home-dirs` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `home-dirs` deployment maintains a stable tree of personal directories under the home directory.

[[home-dirs-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `home-dirs`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `500`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/home-dirs/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/home-dirs/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/home-dirs/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `home-dirs` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Creating*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `*_<dir-path>_*` entries from `<<home-dirs-mtdt,_<asset-dir>_>>/*home-dirs.cfg*
! =>
! `~/*_<dir-path>_*/`
!

!===

Installation:: Created, or re-used if pre-existing.
Removal:: Removed, or untouched if re-used.

|===

The `home-dirs` deployment:

* parses the `*home-dirs.cfg*` file as a https://github.com/no-simpler/divine-dotfiles#queue-mnf[queue manifest];
* treats entries as relative paths;
* ensures that the paths correspond to sub-directories under the home directory.

== Included assets

The `home-dirs.cfg` is a https://github.com/no-simpler/divine-dotfiles#queue-mnf[queue manifest].
It uses the key-value pairs to denote sections or entries that are only relevant for particular OS's.
By default, every entry is relevant everywhere.

A whitespace-separated list of OS's may be provided.
The entire list may be negated by prepenting it with an exclamation mark (`!`).

A key-value that appears on a line of its own comes into effect for the remainder of the manifest, or until overridden.
A key-value on the same line with an entry affects only that entry.

[source]
----
(os: debian)        relative/path/to/directory1   # Debian only
(os: macos bsd)     relative/path/to/directory2   # macOS/BSD only
(os: ! wsl cygwin)  relative/path/to/directory3   # Everything except WSL or Cygwin
(os: all)           relative/path/to/directory4   # 'all'/'any' are reserved values that denote any OS
----

[.note]
[%noheader,cols="<.<a"]
|===
| The queue manifest syntax is documented in the framework's https://github.com/no-simpler/divine-dotfiles#queue-mnf[documentation].
|===

== Dependencies

The `home-dirs` deployment is stand-alone.

:leveloffset!:

:leveloffset: 2

[[zsh-addons-main]]
= Deployment `zsh-addons` (`1000`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-addons` deployment retrieves a number of community addons for Zsh: https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].

[[zsh-addons-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `zsh-addons`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `1000`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/zsh-addons/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/zsh-addons/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/zsh-addons/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `zsh-addons` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/zsh-users/zsh-completions[`zsh-users/zsh-completions`]
! =>
! `~/.zsh/zsh-users/**zsh-completions**/`
!

! Repository https://github.com/zsh-users/zsh-syntax-highlighting[`zsh-users/zsh-syntax-highlighting`]
! =>
! `~/.zsh/zsh-users/**zsh-syntax-highlighting**/`
!

! Repository https://github.com/zsh-users/zsh-autosuggestions[`zsh-users/zsh-autosuggestions`]
! =>
! `~/.zsh/zsh-users/**zsh-autosuggestions**/`
!

!===

Installation:: Cloned/downloaded; any pre-existing original backed up and replaced.
Removal:: Displaced; any backed up original restored.

|===

== Included assets

The `zsh-addons` deployment does not include any assets.

== Dependencies

The `zsh-addons` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved addons are initialized from the runcom script at `grail/assets/config-shell/06-addons.zsh`.

:leveloffset!:

:leveloffset: 2

[[zsh-default-main]]
= Deployment `zsh-default` (`1333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-default` deployment ensures that https://sourceforge.net/projects/zsh[Zsh] is the default shell for the current OS user.

[[zsh-default-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `zsh-default`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `1333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/zsh-default/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/zsh-default/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/zsh-default/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

After some preparations (involving the `/etc/shells` file), the `zsh-default` deployment calls the `chsh -s _<path to zsh>_` command to change the default shell.
Note that *changing the default shell requires the user's password*.
The password prompt will appear during the installation/removal.

== Included assets

The `zsh-default` deployment does not include any assets.

== Dependencies

The `zsh-default` deployment is stand-alone.

On some systems, the <<dpls-dfls,Divinefile>> included with the current bundle ensures that the `chsh` utility is installed.

:leveloffset!:

:leveloffset: 2

[[brewfile-main]]
= Deployment `brewfile` (`3000!`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `brewfile` deployment maintains a set of system dependencies on macOS using the https://github.com/Homebrew/homebrew-bundle[Brewfile].

[[brewfile-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `brewfile`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `3000`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: `!`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/brewfile/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/brewfile/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/brewfile/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

The `brewfile` deployment is flagged as dangerous for two reasons:

* Checking whether a Brewfile is installed or not is not reliable.
* Uninstalling a Brewfile is not implemented on Homebrew's side, and this deployment's implementation is an approximation.

As a result of the flag, the `brewfile` deployment is not processed by the intervention utility, unless the `--with-!` option is given.

== Installation map

.Installation map for the `brewfile` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Installing*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<brewfile-mtdt,_<asset-dir>_>>/*Brewfile*`
! =>
! `$ brew bundle install`
!

!===

Installation:: Installed using `brew bundle`.
Removal:: Removed by calling `$ brew [cask] uninstall` and `$ brew untap`.

|===

The `brewfile` deployment delegates to the https://brew.sh/[`brew` utility] to install whatever items are listed in the provided Brewfile.

Uninstalling a Brewfile, however, is currently not supported by Homebrew.
The `brewfile` deployment provides a workaround.
Upon removal of this deployment, the Brewfile is read in reverse order: for every supported line, the appropriate Homebrew uninstallation command is called.
This procedure is _not_ an exact reverse of the installation due to the possible transient dependencies, as well as other factors.

Currently, the removal of the following Brewfile lines is supported:

* `tap _<name>_` — taps will be untapped.
* `cask _<name>_` — casks will be uninstalled.
* `brew _<name>_` — bottles will be uninstalled.

== Included assets

The included `*Brewfile*` starts up empty, and as such does nothing.
The fundamental dependencies of the current bundle are handled by the included Divinefile.
In other words, the Brewfile is kind of scoffed on around here.

== Dependencies

The `brewfile` deployment is stand-alone.

On macOS, the _Divine.dotfiles_ framework itself ensures that https://brew.sh/[Homebrew] is installed.

:leveloffset!:

:leveloffset: 2

[[bash-it-main]]
= Deployment `bash-it` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `bash-it` deployment introduces the https://github.com/Bash-it/bash-it[Bash-it framework] and custom assets for it into the home directory.

[[bash-it-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `bash-it`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `3333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/bash-it/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/bash-it/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/bash-it/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `bash-it` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/Bash-it/bash-it[`Bash-it/bash-it`]
! =>
! `~/**.bash-it**/`
! <<bash-it-fmwk,^1^>>

!===

Installation:: Cloned/downloaded; any pre-existing original backed up and replaced.
Removal:: Displaced; any backed up original restored.

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<bash-it-mtdt,_<asset-dir>_>>/aliases/**__<name>__.aliases.bash**`
! =>
! `~/.bash-it/aliases/available/**__<name>__.aliases.bash**`
.4+! <<bash-it-blanks,^2^>>

! `<<bash-it-mtdt,_<asset-dir>_>>/completion/**__<name>__.completion.bash**`
! =>
! `~/.bash-it/completion/available/**__<name>__.completion.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/lib/**__<name>__.bash**`
! =>
! `~/.bash-it/lib/**__<name>__.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/plugins/**__<name>__.plugin.bash**`
! =>
! `~/.bash-it/plugins/available/**__<name>__.plugin.bash**`

! `<<bash-it-mtdt,_<asset-dir>_>>/themes/**__<name>__**/__<name>__.theme.bash`
! =>
! `~/.bash-it/themes/**__<name>__**/`
! <<bash-it-themes,^3^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

The `bash-it` deployment clones or downloads the https://github.com/Bash-it/bash-it[`Bash-it/bash-it`] repository into the `~/.bash-it/` directory.
Having succeeded, it symlinks additional assets into the framework.

[[bash-it-fmwk]]
The Bash-it framework is installed with its included installation script.
The `--no-modify-config` option is added because the current bundle already includes the necessary initialization commands.

== Included assets

[[bash-it-blanks]]
Blank sample files are provided for each kind of custom assets:

- `*aliases/divine.aliases.bash*`
- `*completion/divine.completion.bash*`
- `*lib/divine.bash*`
- `*plugins/divine.plugin.bash*`

[[bash-it-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare/laidbare.theme.bash*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `bash-it` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved Bash-it framework is initialized from the runcom script at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-shell/01-bash-it.bash`.
The same file may and should be used to customize the Bash-it framework's loadout.

:leveloffset!:

:leveloffset: 2

[[oh-my-zsh-main]]
= Deployment `oh-my-zsh` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix D.d link in readme head
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `oh-my-zsh` deployment introduces the https://ohmyz.sh[oh-my-zsh framework] and custom assets for it into the home directory.

[[oh-my-zsh-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `oh-my-zsh`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `3333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/oh-my-zsh/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/oh-my-zsh/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/oh-my-zsh/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `oh-my-zsh` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`]
! =>
! `~/**.oh-my-zsh**/`
! <<oh-my-zsh-fmwk,^1^>>

!===

Installation:: Cloned/downloaded; any pre-existing original backed up and replaced.
Removal:: Displaced; any backed up original restored.

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<oh-my-zsh-mtdt,_<asset-dir>_>>/plugins/**__<name>__**/__<name>__.plugin.zsh`
! =>
! `~/.oh-my-zsh/custom/plugins/**__<name>__**/`
! <<oh-my-zsh-plugins,^2^>>

! `<<oh-my-zsh-mtdt,_<asset-dir>_>>/themes/**__<name>__.zsh-theme**`
! =>
! `~/.oh-my-zsh/custom/themes/**__<name>__.zsh-theme**`
! <<oh-my-zsh-themes,^3^>>

!===

Installation:: Symlinked; any pre-existing original backed up and replaced.
Removal:: Unlinked; any backed up original restored.

|===

The `oh-my-zsh` deployment clones or downloads the https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`] repository into the `~/.oh-my-zsh/` directory.
Having succeeded, it symlinks additional assets into the framework.

[[oh-my-zsh-fmwk]]
The oh-my-zsh framework is installed only by cloning its https://github.com/robbyrussell/oh-my-zsh[Github repository].
The included installation script (which normally adds initialization commands to the `~/.zshrc` runcom) is not executed, because the current bundle already includes necessary initialization commands.

== Included assets

[[oh-my-zsh-plugins]]
A blank example file is provided for the custom plugins:

- `*plugins/divine/divine.plugin.zsh*`

[[oh-my-zsh-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare.zsh-theme*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `oh-my-zsh` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved oh-my-zsh framework is initialized from the runcom script at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-shell/01-oh-my-zsh.zsh`.
The same file may and should be used to customize the oh-my-zsh framework's loadout.

:leveloffset!: