= Deployment bundle `essentials`
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revnumber: 9
:revdate: 2019.09.02
:revremark: Change adoc NOTEs to one-cell tables for mobile
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

++++
<p align="center">
<em>Deployment bundle for <a href="https://github\.com/no-simpler/divine-dotfiles">Divine.dotfiles framework</a></em>
<br>
<em>(Bash framework for dotfiles and everything Bash)</em>
</p>
++++

[.lead]
Deployment bundle `*essentials*` for https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] is a collection of opinionated system set-up scripts.
It is intended as a useful starting point for any machine that runs https://www.gnu.org/software/bash[Bash].

== Description

Once the bundle is fully installed, and the shell reloaded, the effects are as follows:

* You are greeted by https://sourceforge.net/projects/zsh[Zsh] as the default shell.
* Basic necessities, such as https://git-scm.com[Git], https://www.vim.org[Vim], and https://gnupg.org[GnuPG] are available.
* Both https://ohmyz.sh[oh-my-zsh] and https://github.com/Bash-it/bash-it[Bash-it] frameworks are now installed and loaded.
* A minimalistic theme for both shell frameworks is active.
* Opinionated configs are plugged in for Git, Vim, Bash, and Zsh.
* Overwritten files and installations are safely backed up or re-used.

All of the above is controlled and customized from your Grail directory:

[source]
----
~/.divine/grail/assets/
----

.Description of asset directories for the bundle `essentials`
[%header,cols="<.<1,^.<1,<.<3",stripes=none]
|===

^.^| Asset directory
+++<br>+++
`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`
^.^| `&nbsp;`
^.^| Content description

| `*bash-it*/`
| *&dagger;*
| Custom assets for https://github.com/Bash-it/bash-it[Bash-it] shell framework

| `*brewfile*/`
| *&dagger;*
| https://github.com/Homebrew/homebrew-bundle[Brewfile], maintained on macOS

| `*config-git*/`
|
| Global configuration for Git

| `*config-shell*/`
|
| Startup scripts (https://en.wikipedia.org/wiki/Run_commands[runcoms]) for Bash and Zsh

| `*config-vim*/`
|
| Global configuration for Vim

| `*home-dirs*/`
| *&dagger;*
| File `*home-dirs.cfg*` defines a sub-directory tree, to be maintained under the home directory

| `*oh-my-zsh*/`
| *&dagger;*
| Custom assets for https://ohmyz.sh[oh-my-zsh] shell framework

| `*portable-bin*/`
|
| Portable container for personal executables; this directory is maintained on the `$PATH`

|===

[.note]
|===
| Dagger *&dagger;* mark meaning: in order for the modifications in the asset directory to take effect, the deployment must be (re-)installed.
|===

Refer to each deployment's section for more information.

== Installing and uninstalling the bundle

=== System requirements

This deployment bundle is for the https://github.com/no-simpler/divine-dotfiles[_Divine.dotfiles_] Bash framework.

=== Installing the bundle

==== Framework already installed

If you already have _Divine.dotfiles_ installed, *attach this bundle* to your Grail directory:

[source,bash]
----
di attach essentials --yes
----

Then *install the bundled deployments*:

[source,bash]
----
di install --bundle essentials --yes
----

==== Installing framework and bundle

For first-time users of _Divine whatever_: to *install both _Divine.dotfiles_ framework and this bundle* in one go and without prompts, run the following chained command in Terminal:

[source,bash]
----
bash -c 'TMP=$(mktemp); URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/install/install.sh; if curl --version &>/dev/null; then curl -fsSL $URL >$TMP; elif wget --version &>/dev/null; then wget -qO $TMP $URL; else printf >&2 "\n==> Error: failed to detect neither curl nor wget\n"; rm -f $TMP; exit 1; fi || { printf >&2 "\n==> Error: failed to download installation script\n"; rm -f $TMP; exit 2; }; chmod +x $TMP && $TMP "$@"; RC=$?; rm -f $TMP; ((RC)) && exit 3 || exit 0' bash --yes \
&& ~/.divine/intervene.sh attach essentials --yes \
&& ~/.divine/intervene.sh install --yes
----

[.note]
|===
| Pre-existing files on the system are either re-used or backed up to be restored upon uninstallation.
|===

=== Uninstalling the bundle

==== Keeping framework

If you intend to keep _Divine.dotfiles_ installed, *uninstall the bundled deployments*:

[source,bash]
----
di remove --bundle essentials --yes
----

Then *detach this bundle* from your Grail directory:

[source,bash]
----
di detach essentials --yes
----

==== Uninstalling framework and bundle

To *uninstall both _Divine.dotfiles_ framework and this bundle* in one go and without prompts, run the following chained command in Terminal:

[source,bash]
----
~/.divine/intervene.sh remove --yes \
&& ~/.divine/intervene.sh detach essentials --yes \
&& bash -c 'TMP=$(mktemp); URL=https://raw.github.com/no-simpler/divine-dotfiles/master/lib/uninstall/uninstall.sh; if curl --version &>/dev/null; then curl -fsSL $URL >$TMP; elif wget --version &>/dev/null; then wget -qO $TMP $URL; else printf >&2 "\n==> Error: failed to detect neither curl nor wget\n"; rm -f $TMP; exit 1; fi || { printf >&2 "\n==> Error: failed to download uninstallation script\n"; rm -f $TMP; exit 2; }; chmod +x $TMP && $TMP "$@"; RC=$?; rm -f $TMP; ((RC)) && exit 3 || exit 0' bash --yes
----

== Bundled deployments

=== Divinefile

The bundle includes a Divinefile that maintains the following system packages.

.List of Divinefile packages for the bundle `essentials`
[%header,cols="^.^1a,<.^2a,<.<3a",stripes=none]
|===

^.^| Priority
^.^| Package name
^.^| Package notes

| `*1000*`
| `git`
|

| `*1000*`
| `vim`
|

| `*1000*`
| `zsh`
|

| `*1000*`
| `wget`
| _(except macOS)_

| `*1000*`
| `curl`
| _(except macOS)_

| `*1000*`
| `gnupg`
|

| `*1000*`
| `util-linux-user`
| _(Fedora only)_

This one contains `chsh` which is required for the deployment `zsh-default`.

|===

include::config-git/README.adoc[leveloffset=2]

include::config-shell/README.adoc[leveloffset=2]

include::config-vim/README.adoc[leveloffset=2]

include::portable-bin/README.adoc[leveloffset=2]

include::home-dirs/README.adoc[leveloffset=2]

include::zsh-default/README.adoc[leveloffset=2]

include::brewfile/README.adoc[leveloffset=2]

include::bash-it/README.adoc[leveloffset=2]

include::oh-my-zsh/README.adoc[leveloffset=2]

include::dutils/README.adoc[leveloffset=2]