= Deployment `config-vim` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-vim` deployment symlinks the configuration and customization files for https://www.vim.org[Vim] into the home directory.

The `config-vim` deployment has the priority of `*333*`.

== Deployment installation notes

The `config-vim` deployment supplants any pre-existing Vim configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the `config-vim` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*.vimrc*`
| symlinked
| `~/*.vimrc*`
| The main Vim config <<config-vim-vimrc,^1^>>

| `*.ideavimrc*`
| symlinked
| `~/*.ideavimrc*`
| The optional IdeaVim config <<config-vim-ideavimrc,^2^>>

| `.vim/**__<name>__**/`
| symlinked
| `~/.vim/**__<name>__**/`
| The Vim customization directories <<config-vim-customization-dirs,^3^>>

|===

== Included assets

The `config-vim` deployment's *asset directory* is located at `grail/assets/config-vim`.

The native configuration files, containing an opinionated set of Vim startup commands:

* [[config-vim-vimrc]]`*.vimrc*` — the primary Vim configuration file.
+
This file includes an installation command for the https://github.com/junegunn/vim-plug[vim-plug] (_a minimalist Vim plugin manager_) along with a number of plugins and settings.
* [[config-vim-ideavimrc]]`*.ideavimrc*` — the configuration file for the https://github.com/JetBrains/ideavim[IdeaVim] (_a Vim emulation plugin for IDEs based on the IntelliJ Platform_).
+
If you don't use any of the IntelliJ products, this file is harmless.

[[config-vim-customization-dirs]]
A number of Vim *customization directories* can be created in the root of the `.vim/` directory, as containers for your customizations.
Most of these directories are not included with the deployment to prevent clutter.
One keymap is provided as an example:

* `*keymap/shifted.vim*` — the 'Caps Lock' mode toggled by double-tapping `j`.

Overall, the following customization directories are supported by Vim:

* `*after/*` — the files to be loaded after the files in `plugin/`.
* `*autoload/*` — the files to be loaded when they are actually needed.
* `*colors/*` — the color schemes.
* `*compiler/*` — the compiler-related options in the current buffer.
* `*doc/*` — the custom plugin documentation.
* `*ftdetect/*` — the file type detection plugins.
* `*ftplugin/*` — the file type exclusive plugins.
* `*indent/*` — the file type exclusive indentation settings.
* `*keymap/*` — the key mapping files.
* `*lang/*` — the language files.
* `*macros/*`
* `*plugin/*` — the standard plugins.
* `*syntax/*` — the syntax highlighting plugins.
* `*tools/*`

Refer to the Vim https://vimhelp.org[help] for more information on the semantics of each directory.

== Dependencies

The `config-vim` deployment is stand-alone.

The Divinefile included with the current bundle ensures that Vim is installed.

== Supported asset modifications

The `.vimrc` and `.ideavim` files may be freely modified in the asset directory; the modifications will take effect on the next Vim startup.
Renaming or moving any of the configuration files will break them.

The `.ideavim` file can be safely removed from the asset directory before installing the deployment.

The symlinked content of the Vim customization directories may be freely modified in the asset directory; the modifications will take effect on the next Vim startup.

The additional customization directories or files may be freely added to the root of the `.vim/` directory.
For the additions to be symlinked into `~/.vim/` directory, the deployment must be (re-)installed.

== Overwriting policy

The `config-vim` deployment backs up any clashing pre-existing files in the home directory.
The backup directory is at `state/backups/config-vim/`.

A pre-existing `~/.vim/` directory is not replaced as a whole, but the files and directories in its root are.

== Deployment removal notes

The `config-git` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.