#:title:        Divine asset sample: Brewfile
#:author:       Grove Pyree
#:email:        grayarea@protonmail.ch
#:revnumber:    2
#:revdate:      2019.07.22
#:revremark:    New revisioning system
#:created_at:   2019.04.11

# Regular Brewfile, as produced by `brew bundle dump`
