= Deployment `config-git` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `config-git` deployment symlinks the configuration files for https://git-scm.com[Git] into the home directory.

The `config-git` deployment has the priority of `*333*`.

== Deployment installation notes

The `config-git` deployment supplants any pre-existing Git configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the `config-git` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*.gitconfig*`
| symlinked
| `~/*.gitconfig*`
| The global Git config <<config-git-config,^1^>>

| `*.gitattributes*`
| symlinked
| `~/*.gitattributes*`
| The global Git attributes file <<config-git-attributes,^2^>>

|===

== Included assets

The `config-git` deployment's *asset directory* is located at `grail/assets/config-git`.

The two global configuration files for https://git-scm.com[Git] are provided:

- [[config-git-config]]`*.gitconfig*` — this file is interacted with by the https://git-scm.com/docs/git-config[`git config --global`] command.
- [[config-git-attributes]]`*.gitattributes*` — this file globally influences certain Git operations by https://git-scm.com/docs/gitattributes[assigning attributes] to the certain file path patterns.

A small amount of opinionated configuration is included in the specified files.

== Dependencies

The `config-git` deployment is stand-alone.

The Divinefile included with the current bundle ensures that Git is installed.

== Supported asset modifications

The included configuration files may be freely modified in the asset directory; the modifications will take effect immediately.
Renaming or moving any of the configuration files will break them.

The `config-git` deployment does not support any additional assets.

== Overwriting policy

The `config-git` deployment backs up any clashing pre-existing files in the home directory.
The backup directory is at `state/backups/config-git/`.

== Deployment removal notes

The `config-git` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.