= Deployment `config-git` (`333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.10.24
:revremark: Rewrite for D.d v2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

This deployment symlinks configuration files for https://git-scm.com[Git] into the home directory.

This deployment has the priority of `*333*`.

== Deployment installation notes

The deployment supplants existing Git configuration, while keeping backups of whatever is replaced.

.Map of asset installation for the deployment `config-git`
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Asset description

| `*.gitconfig*`
| symlinked
| `~/*.gitconfig*`
| Main Git config <<config-git-config,^1^>>

| `*.gitattributes*`
| symlinked
| `~/*.gitattributes*`
| Main Git attributes file <<config-git-attributes,^2^>>

|===

== Included assets

The deployment's asset directory is located at:

[source]
--
grail/assets/config-git
--

Two global configuration files for https://git-scm.com[Git] are provided:

- [#config-git-config]#`*.gitconfig*`# — this file is interacted with by https://git-scm.com/docs/git-config[`git config --global`].
- [#config-git-attributes]#`*.gitattributes*`# — globally influences certain Git operations by https://git-scm.com/docs/gitattributes[assigning attributes] to certain file path patterns.

A small amount of opinionated configuration is included in the specified files.

== Dependencies

This deployment is stand-alone.

Divinefile included with the current bundle ensures that Git is installed.

== Supported asset modifications

Both configuration files may be freely modified in place.
Modifications will take effect immediately.
Renaming or moving any of the two configuration files will break the deployment.

This deployment does not support any additional assets.

== Overwriting policy

If during installation of the deployment any of the two configuration files exist in the home directory, they are backed up into the deployment's designated backup directory at:

[source]
----
state/backups/config-git/
----

== Deployment removal notes

Upon uninstallation of the deployment, backups of any overwritten Git global configuration files are automatically restored.

Uninstallation does not remove anything in the asset directory.