= Deployment `zsh-default` (`1333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-default` deployment ensures that https://sourceforge.net/projects/zsh[Zsh] is the default shell for the current OS user.

The `zsh-default` deployment has the priority of `*1333*`.

== Deployment installation notes

After some preparations (involving the `/etc/shells` file), the `zsh-default` deployment calls the `chsh -s _<path to zsh>_` command to change the default shell.
Note that *changing the default shell requires the user's password*.
The password prompt will appear during the installation/removal.

== Included assets

The `zsh-default` deployment does not use the asset directory.

== Dependencies

The `zsh-default` deployment is stand-alone.

On some systems, the Divinefile included with the current bundle ensures that the `chsh` utility is installed.

== Supported asset modifications

The `zsh-default` deployment provides no modifiable assets.

== Overwriting policy

The `zsh-default` deployment does not overwrite any files.

If the default shell is already Zsh, this deployment does nothing.

== Deployment removal notes

The `config-git` deployment is fully reversible: the original default shell is restored.
If the default shell is not changed during the installation, it is not changed during the removal as well.