#:title:        Divine asset sample: Brewfile
#:author:       Grove Pyree
#:email:        grayarea@protonmail.ch
#:revdate:      2019.10.24
#:revremark:    Rewrite for D.d v2
#:created_at:   2019.04.11

# Regular Brewfile, as produced by `brew bundle dump`
