[[brewfile-main]]
= Deployment `brewfile` (`3000!`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Rewrite all Gh references to point to moved repo
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `brewfile` deployment maintains a set of system dependencies on macOS using the https://github.com/Homebrew/homebrew-bundle[Brewfile].

[[brewfile-mtdt]]
[none]
* *Deployment* https://github.com/divine-dotfiles/divine-dotfiles#mtdt-name-and-desc[*name*]: `brewfile`
* https://github.com/divine-dotfiles/divine-dotfiles#mtdt-priority[*Priority*]: `3000`
* https://github.com/divine-dotfiles/divine-dotfiles#mtdt-flags[*Flags*]: `!`
* https://github.com/divine-dotfiles/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/divine-dotfiles/divine-dotfiles#fmwk-state[state]/bundles/divine-bundles/essentials/brewfile/`
* https://github.com/divine-dotfiles/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `~/https://github.com/divine-dotfiles/divine-dotfiles#fmwk-grail[.grail]/assets/brewfile/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/divine-dotfiles/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/divine-dotfiles/divine-dotfiles#fmwk-state[state]/backups/brewfile/`
* https://github.com/divine-dotfiles/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/divine-dotfiles/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

The `brewfile` deployment is flagged as dangerous for two reasons:

* Checking whether a Brewfile is installed or not is not reliable.
* Uninstalling a Brewfile is not implemented on Homebrew's side, and this deployment's implementation is an approximation.

As a result of the flag, the `brewfile` deployment is not processed by the intervention utility, unless the `--with-!` option is given.

== Installation map

.Installation map for the `brewfile` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Installing*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<brewfile-mtdt,_<asset-dir>_>>/*Brewfile*`
! =>
! `$ brew bundle install`
! 

!===

Installation:: Installed using `brew bundle`.
Removal:: Removed by calling `$ brew [cask] uninstall` and `$ brew untap`.

|===

The `brewfile` deployment delegates to the https://brew.sh/[`brew` utility] to install whatever items are listed in the provided Brewfile.

Uninstalling a Brewfile, however, is currently not supported by Homebrew.
The `brewfile` deployment provides a workaround.
Upon removal of this deployment, the Brewfile is read in reverse order: for every supported line, the appropriate Homebrew uninstallation command is called.
This procedure is _not_ an exact reverse of the installation due to the possible transient dependencies, as well as other factors.

Currently, the removal of the following Brewfile lines is supported:

* `tap _<name>_` — taps will be untapped.
* `cask _<name>_` — casks will be uninstalled.
* `brew _<name>_` — bottles will be uninstalled.

== Included assets

The included `*Brewfile*` starts up empty, and as such does nothing.
The fundamental dependencies of the current bundle are handled by the included Divinefile.
In other words, the Brewfile is kind of scoffed on around here.

== Dependencies

The `brewfile` deployment is stand-alone.

On macOS, the _Divine.dotfiles_ framework itself ensures that https://brew.sh/[Homebrew] is installed.