= Deployment `brewfile` (`3000!`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `brewfile` deployment maintains a set of system dependencies on macOS using the https://github.com/Homebrew/homebrew-bundle[Brewfile].

The `brewfile` deployment is flagged as dangerous for two reasons:

* Checking whether a Brewfile is installed or not is not reliable.
* Uninstalling a Brewfile is not implemented on Homebrew's side, and this deployment's implementation is an approximation.

As a result of the flag, the `brewfile` deployment is not processed by the intervention utility, unless the `--with-!` option is given.

The `brewfile` deployment has the priority of `*3000*`.

== Deployment installation notes

The `brewfile` deployment delegates to the https://brew.sh/[`brew` utility] to install whatever items are listed in the provided Brewfile.

.Map of asset installation for the `brewfile` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `*Brewfile*`
| used
| https://brew.sh/[`brew` utility]
| The manifest of system dependencies

|===

== Included assets

The `brewfile` deployment's *asset directory* is located at `grail/assets/brewfile`.

The included `*Brewfile*` starts up empty, and as such does nothing.
The fundamental dependencies of the current bundle are handled by the included Divinefile.
In other words, the Brewfile is kind of scoffed on around here.

== Dependencies

The `brewfile` deployment is stand-alone.

On macOS, the _Divine.dotfiles_ framework itself ensures that https://brew.sh/[Homebrew] is installed.

== Supported asset modifications

The Brewfile may be freely modified in the asset directory.
For the changes to take effect, the deployment must be (re-)installed.
Renaming or moving the Brewfile will break the deployment.

== Overwriting policy

The handling of Brewfiles is intirely in Homebrew's hands.
Still, no major clobbering is expected.

== Deployment removal notes

Uninstalling a Brewfile is currently not supported by Homebrew.

The `brewfile` deployment provides a workaround.
Upon removal of this deployment, the Brewfile is read in reverse order: for every supported line, the appropriate Homebrew uninstallation command is called.
This procedure is _not_ an exact reverse of the installation due to the possible transient dependencies, as well as other factors.

Currently, the removal of the following Brewfile lines is supported:

* `tap _<name>_` — taps will be untapped.
* `cask _<name>_` — casks will be uninstalled.
* `brew _<name>_` — bottles will be uninstalled.

The removal does not touch anything in the asset directory.