= Deployment `oh-my-zsh` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.10.24
:revremark: Rewrite for D.d v2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

This deployment introduces https://ohmyz.sh[oh-my-zsh framework] and custom assets for it into the home directory.

This deployment has the priority of `*3333*`.

== Deployment installation notes

This deployment ensures https://ohmyz.sh[oh-my-zsh framework] is installed into `~/.oh-my-zsh/`.
Having succeeded, it symlinks additional assets into oh-my-zsh directory.

.Map of asset installation for the deployment `oh-my-zsh`
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Asset description

| https://github.com/robbyrussell/oh-my-zsh[oh-my-zsh repo]
| cloned
| `~/**.oh-my-zsh**/`
| oh-my-zsh framework <<oh-my-zsh-fmwk,^1^>>

| `plugins/**__<name>__**/__<name>__.plugin.zsh`
| symlinked
| `~/.oh-my-zsh/custom/plugins/**__<name>__**/`
| Custom oh-my-zsh plugins <<oh-my-zsh-plugins,^2^>>

| `themes/**__<name>__.zsh-theme**`
| symlinked
| `~/.oh-my-zsh/custom/themes/**__<name>__.zsh-theme**`
| Custom oh-my-zsh themes <<oh-my-zsh-themes,^3^>>

|===

Path components in bold designate the source and target during cloning or symlinking.

[#oh-my-zsh-fmwk]#oh-my-zsh framework# is installed by cloning its https://github.com/robbyrussell/oh-my-zsh[Github repository].
Included installation script (which normally adds startup commands to `~/.zshrc`) is not run because current bundle already includes necessary start-up commands.

== Included assets

The deployment's asset directory is located at:

[source]
--
grail/assets/oh-my-zsh
--

A blank example file is provided for [#oh-my-zsh-plugins]#custom plugins#:

- `*plugins/divine/divine.plugin.zsh*`

In case of [#oh-my-zsh-themes]#themes#, a working minimalistic theme is provided (and is defaulted to by the included startup configuration):

- `*themes/laidbare.zsh-theme*`

== Dependencies

*This deployment depends on* `*config-shell*` *deployment* (included in current bundle).
Shell start-up commands that load and configure oh-my-zsh framework are located in and sourced from:

[source]
--
grail/assets/config-shell/.runcoms/00-oh-my-zsh.zsh
--

The same file may and should be used to customize oh-my-zsh framework's loadout.

== Supported asset modifications

All existing assets may be freely modified in place.
Modifications will take effect after shell reload.
Renaming or moving any of the asset files will break their respective functions.

Additional asset files may be freely added, as long as they follow the naming patterns above.
For the additions to be symlinked into oh-my-zsh directory, the deployment must be (re-)installed.

== Overwriting policy

If during installation of the deployment oh-my-zsh framework is already present at `~/.oh-my-zsh/`, it is re-used.

During installation of the deployment, whenever a symlink is created at a certain path, anything that pre-exists at that location is preserved in the deployment's designated backup directory at:

[source]
--
state/backups/oh-my-zsh/
--

== Deployment removal notes

oh-my-zsh framework is removed by erasing `~/.oh-my-zsh/` directory.
If pre-existing oh-my-zsh installation has been re-used, it is *not removed*.

Upon uninstallation of the deployment, backups of any overwritten files or directories are automatically restored.

Uninstallation does not remove anything in the asset directory.