[[oh-my-zsh-main]]
= Deployment `oh-my-zsh` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix oh-my-zsh repo handle in readme
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `oh-my-zsh` deployment introduces the https://ohmyz.sh[oh-my-zsh framework] and custom assets for it into the home directory.

[[oh-my-zsh-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `oh-my-zsh`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `3333`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/oh-my-zsh/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/oh-my-zsh/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/oh-my-zsh/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `oh-my-zsh` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`]
! =>
! `~/**.oh-my-zsh**/`
! <<oh-my-zsh-fmwk,^1^>>

!===

Installation:: Cloned/downloaded, displacing any original.
Removal:: Displaced; backed up original restored, if any.

| +++<p align="center">+++
*Symlinking*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! `<<oh-my-zsh-mtdt,_<asset-dir>_>>/plugins/**__<name>__**/__<name>__.plugin.zsh`
! =>
! `~/.oh-my-zsh/custom/plugins/**__<name>__**/`
! <<oh-my-zsh-plugins,^2^>>

! `<<oh-my-zsh-mtdt,_<asset-dir>_>>/themes/**__<name>__.zsh-theme**`
! =>
! `~/.oh-my-zsh/custom/themes/**__<name>__.zsh-theme**`
! <<oh-my-zsh-themes,^3^>>

!===

Installation:: Symlinked, displacing any original.
Removal:: Unlinked; backed up original restored, if any.

|===

The `oh-my-zsh` deployment clones or downloads the https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`] repository into the `~/.oh-my-zsh/` directory.
Having succeeded, it symlinks additional assets into the framework.

[[oh-my-zsh-fmwk]]
The oh-my-zsh framework is installed only by cloning its https://github.com/robbyrussell/oh-my-zsh[Github repository].
The included installation script (which normally adds initialization commands to the `~/.zshrc` runcom) is not executed, because the current bundle already includes necessary initialization commands.

== Included assets

[[oh-my-zsh-plugins]]
A blank example file is provided for the custom plugins:

- `*plugins/divine/divine.plugin.zsh*`

[[oh-my-zsh-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare.zsh-theme*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `oh-my-zsh` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved oh-my-zsh framework is initialized from the runcom script at `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/config-shell/01-oh-my-zsh.zsh`.
The same file may and should be used to customize the oh-my-zsh framework's loadout.