= Deployment `oh-my-zsh` (`3333`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `oh-my-zsh` deployment introduces the https://ohmyz.sh[oh-my-zsh framework] and custom assets for it into the home directory.

The `oh-my-zsh` deployment has the priority of `*3333*`.

== Deployment installation notes

The `oh-my-zsh` deployment clones or downloads the https://github.com/robbyrussell/oh-my-zsh[`robbyrussell/oh-my-zsh`] repository into the `~/.oh-my-zsh/` directory.
Having succeeded, it symlinks additional assets into the framework.

.Map of asset installation for the `oh-my-zsh` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| https://github.com/robbyrussell/oh-my-zsh[oh-my-zsh repo]
| cloned
| `~/**.oh-my-zsh**/`
| oh-my-zsh framework <<oh-my-zsh-fmwk,^1^>>

| `plugins/**__<name>__**/__<name>__.plugin.zsh`
| symlinked
| `~/.oh-my-zsh/custom/plugins/**__<name>__**/`
| Custom oh-my-zsh plugins <<oh-my-zsh-plugins,^2^>>

| `themes/**__<name>__.zsh-theme**`
| symlinked
| `~/.oh-my-zsh/custom/themes/**__<name>__.zsh-theme**`
| Custom oh-my-zsh themes <<oh-my-zsh-themes,^3^>>

|===

The path components in bold designate the source and the target of cloning/symlinking.

[[oh-my-zsh-fmwk]]
The oh-my-zsh framework is installed by cloning its https://github.com/robbyrussell/oh-my-zsh[Github repository].
The included installation script (which normally adds initialization commands to the `~/.zshrc` runcom) is not executed, because the current bundle already includes necessary initialization commands.

== Included assets

The `oh-my-zsh` deployment's *asset directory* is located at `grail/assets/oh-my-zsh`.

[[oh-my-zsh-plugins]]
A blank example file is provided for the custom plugins:

- `*plugins/divine/divine.plugin.zsh*`

[[oh-my-zsh-themes]]
A working minimalistic theme is provided for the custom themes:

- `*themes/laidbare.zsh-theme*`
+
This theme is also defaulted to in the provided initialization commands.

== Dependencies

The `oh-my-zsh` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The retrieved oh-my-zsh framework is initialized from the runcom script at `grail/assets/config-shell/01-oh-my-zsh.zsh`.
The same file may and should be used to customize the oh-my-zsh framework's loadout.

== Supported asset modifications

All symlinked assets may be freely modified in the asset directory; the modifications will take effect after the shell reload.

However, moving any of the assets will break them.
The deployment should be uninstalled before moving, and re-installed afterward. 

Additional asset files may be freely added, as long as they follow the naming patterns above.
For the additions to be symlinked into the oh-my-zsh directory, the deployment must be (re-)installed.

== Overwriting policy

If the oh-my-zsh framework is already present at `~/.oh-my-zsh/`, it is re-used.

The `oh-my-zsh` deployment backs up any clashing pre-existing files in the `~/.oh-my-zsh` directory.
The backup directory is at `state/backups/oh-my-zsh/`.

== Deployment removal notes

The `oh-my-zsh` deployment is fully reversible: the retrieved repositories are removed, and the displaced pre-existing files are restored.
Any files that have been re-used remain in place.

The removal does not touch anything in the asset directory.