= Deployment `portable-bin` (`500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.12
:revremark: Rewrite for D.d v2, pt. 2
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `portable-bin` deployment uses its own asset directory as a portable container for the personal executables.

The `portable-bin` deployment has the priority of `*500*`.

== Deployment installation notes

Basically, everything dropped into the `portable-bin` deployment's *asset directory* immediately becomes available on `$PATH`.
The portability is achieved when the Grail directory is synchronized across machines (as it is encouraged to be — e.g., using Dropbox or Github).

.Map of asset installation for the `portable-bin` deployment
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Description

| `_<asset dir itself>_`
| symlinked
| `~/*.pbin*/`
| The portable directory for the personal executables

|===

== Included assets

The `portable-bin` deployment's *asset directory* is located at `grail/assets/portable-bin`.
This drop-box type directory starts empty.

== Dependencies

The `portable-bin` deployment depends on the `*config-shell*` deployment (included in the current bundle).
The `~/.pbin/` directory is put on the `$PATH` variable from the runcom script at `grail/assets/config-shell/02-env.sh`.

== Supported asset modifications

The binaries/executables may be freely dropped into the asset directory.
They will become available on the command line immediately.

== Overwriting policy

The `portable-bin` deployment backs up any clashing pre-existing file at the `~/.pbin` path.
The backup directory is at `state/backups/portable-bin/`.

== Deployment removal notes

The `portable-bin` deployment is fully reversible: the displaced pre-existing files are restored.

The removal does not touch anything in the asset directory.