= Deployment `dutils` (`3500`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revnumber: 2
:revdate: 2019.09.01
:revremark: Tie readmes together
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

This deployment exposes a few of the _Divine.dotfiles_ internal utilities into a directory on `$PATH`.

This deployment has the priority of `*3500*`.

== Deployment installation notes

This deployment creates a surrogate executable for each exposed utility.
The executable, each time that it is called, sources the actual utility script from the framework's innards.

The deployment tries to put executables into a bunch of common directories, like `~/bin` or `/usr/local/bin`, and settles for the first candidate that exists and is on `$PATH`.

.Map of asset installation for the deployment `dutils`
[%header,cols="<.^3a,^.^1,<.^3a,<.^3a",stripes=none]
|===

^.^| Asset
^.^| Method
^.^| Destination
^.^| Asset description

| `~/.divine/lib/utils/*dln.utl.sh*`
| surrogated
| `_<$PATH dir>_/*dln*`
| Symlinking instrument <<dutils-dln,^1^>>

| `~/.divine/lib/utils/*dmv.utl.sh*`
| surrogated
| `_<$PATH dir>_/*dmv*`
| File moving instrument <<dutils-dmv,^2^>>

| `~/.divine/lib/utils/*dreadlink.utl.sh*`
| surrogated
| `_<$PATH dir>_/*dreadlink*`
| Cross-platform implementation of `readlink` <<dutils-dreadlink,^3^>>

|===

== Included assets

The deployment's does not use an asset directory.

The following utilities are exposed, all of which provide info on usage on their help screen (use `--help` option):

- [#dutils-dln]#`*dln*`# — creates a symlink without treating directories specially, while also providing a way to create a backup of whatever might be clobbered by the symlink.
- [#dutils-dmv]#`*dmv*`# — places a file into a given location without treating directories specially, while also providing a way to create a backup of whatever might be clobbered at destination.
- [#dutils-dreadlink]#`*dreadlink*`# — a cross-platform implementation of `readlink` that behaves like http://man7.org/linux/man-pages/man1/readlink.1.html[GNU version] on all platforms.

== Dependencies

This deployment is stand-alone.

== Supported asset modifications

This deployment provides no modifiable assets.
The exposed utilities are updated with the _Divine.dotfiles_ framework itself.

== Overwriting policy

For each utility being exposed, if a command by the same name pre-exists on `$PATH`, that utility is not installed.

== Deployment removal notes

Upon uninstallation of the deployment, the surrogate executables are simply erased.