[[zsh-addons-main]]
= Deployment `zsh-addons` (`1000`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.12.01
:revremark: Fix URL links in readmes
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **
:url_dd: https://github.com/divine-dotfiles/divine-dotfiles

The `zsh-addons` deployment retrieves a number of community addons for Zsh: https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].

[[zsh-addons-mtdt]]
[none]
* *Deployment* link:{url_dd}#mtdt-name-and-desc[*name*]: `zsh-addons`
* link:{url_dd}#mtdt-priority[*Priority*]: `1000`
* link:{url_dd}#mtdt-flags[*Flags*]: _none_
* link:{url_dd}#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `link:{url_dd}#fmwk-state[state]/bundles/divine-bundles/essentials/zsh-addons/`
* link:{url_dd}#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `~/link:{url_dd}#fmwk-grail[.grail]/assets/zsh-addons/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* link:{url_dd}#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `link:{url_dd}#fmwk-state[state]/backups/zsh-addons/`
* link:{url_dd}#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* link:{url_dd}#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `zsh-addons` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/zsh-users/zsh-completions[`zsh-users/zsh-completions`]
! =>
! `~/.zsh/zsh-users/**zsh-completions**/`
! 

! Repository https://github.com/zsh-users/zsh-syntax-highlighting[`zsh-users/zsh-syntax-highlighting`]
! =>
! `~/.zsh/zsh-users/**zsh-syntax-highlighting**/`
! 

! Repository https://github.com/zsh-users/zsh-autosuggestions[`zsh-users/zsh-autosuggestions`]
! =>
! `~/.zsh/zsh-users/**zsh-autosuggestions**/`
! 

!===

Installation:: Cloned/downloaded; any pre-existing original backed up and replaced.
Removal:: Displaced; any backed up original restored.

|===

== Included assets

The `zsh-addons` deployment does not include any assets.

== Dependencies

The `zsh-addons` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved addons are initialized from the runcom script at `~/.grail/assets/config-shell/06-addons.zsh`.