[[zsh-addons-main]]
= Deployment `zsh-addons` (`1000`)
:author: Grove Pyree
:email: grayarea@protonmail.ch
:revdate: 2019.11.15
:revremark: Fix adoc syntax for repos
:doctype: article
// Visual
:toc:
// Subs:
:hs: #
:dhs: ##
:us: _
:dus: __
:as: *
:das: **

The `zsh-addons` deployment retrieves a number of community addons for Zsh: https://github.com/zsh-users/zsh-completions[completions], https://github.com/zsh-users/zsh-syntax-highlighting[syntax highlighting], and https://github.com/zsh-users/zsh-autosuggestions[auto-suggestions].

[[zsh-addons-mtdt]]
[none]
* *Deployment* https://github.com/no-simpler/divine-dotfiles#mtdt-name-and-desc[*name*]: `zsh-addons`
* https://github.com/no-simpler/divine-dotfiles#mtdt-priority[*Priority*]: `1000`
* https://github.com/no-simpler/divine-dotfiles#mtdt-flags[*Flags*]: _none_
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-dir[*Deployment directory*] (`_<dpl-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/bundles/no-simpler/divine-bundle-essentials/zsh-addons/`
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-asset-dir[*Asset directory*] (`_<asset-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-grail[grail]/assets/zsh-addons/`
+
Assets are never removed from the Grail, even when uninstalling the deployment.
* https://github.com/no-simpler/divine-dotfiles#indct-dpl-backup-dir[*Backup directory*] (`_<backup-dir>_`): `https://github.com/no-simpler/divine-dotfiles#fmwk-state[state]/backups/zsh-addons/`
* https://github.com/no-simpler/divine-dotfiles#fmwk-zero-data-loss[*Zero data loss*]: any displaced files are backed up.
* https://github.com/no-simpler/divine-dotfiles#fmwk-reversibility[*Reversibility*]: backed up files are restored, re-used ones untouched.

== Installation map

.Installation map for the `zsh-addons` deployment
[%noheader,cols="<.<a",stripes=none]
|===

| +++<p align="center">+++
*Retrieving Github repositories*
+++</p>+++

[%noheader,cols="4*<.^",stripes=none]
!===

! Repository https://github.com/zsh-users/zsh-completions[`zsh-users/zsh-completions`]
! =>
! `~/.zsh/zsh-users/**zsh-completions**/`
! 

! Repository https://github.com/zsh-users/zsh-syntax-highlighting[`zsh-users/zsh-syntax-highlighting`]
! =>
! `~/.zsh/zsh-users/**zsh-syntax-highlighting**/`
! 

! Repository https://github.com/zsh-users/zsh-autosuggestions[`zsh-users/zsh-autosuggestions`]
! =>
! `~/.zsh/zsh-users/**zsh-autosuggestions**/`
! 

!===

Installation:: Cloned/downloaded, displacing any original.
Removal:: Displaced; backed up original restored, if any.

|===

== Included assets

The `zsh-addons` deployment does not include any assets.

== Dependencies

The `zsh-addons` deployment depends on the <<config-shell-main,`*config-shell*`>> deployment (included in the current bundle).
The retrieved addons are initialized from the runcom script at `grail/assets/config-shell/06-addons.zsh`.